In [1]:
import numpy as np
import pandas as pd
from f1winnerprediction import (
   config, 
	io_fastf1
)
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report,roc_auc_score, roc_curve, auc, mean_absolute_error, r2_score, accuracy_score, f1_score
import fastf1
import fastf1.core
import xgboost as xgb

fastf1.Cache.enable_cache(config.FASTF1_RAW_CACHE_DIR)

# Load sessions

In [2]:
sessions: dict[int, list[fastf1.core.Session]] = io_fastf1.load_sessions_from_years()
sessions

{2021: [2021 Season Round 1: Bahrain Grand Prix - Race,
  2021 Season Round 2: Emilia Romagna Grand Prix - Race,
  2021 Season Round 3: Portuguese Grand Prix - Race,
  2021 Season Round 4: Spanish Grand Prix - Race,
  2021 Season Round 5: Monaco Grand Prix - Race,
  2021 Season Round 6: Azerbaijan Grand Prix - Race,
  2021 Season Round 7: French Grand Prix - Race,
  2021 Season Round 8: Styrian Grand Prix - Race,
  2021 Season Round 9: Austrian Grand Prix - Race,
  2021 Season Round 10: British Grand Prix - Race,
  2021 Season Round 11: Hungarian Grand Prix - Race,
  2021 Season Round 12: Belgian Grand Prix - Race,
  2021 Season Round 13: Dutch Grand Prix - Race,
  2021 Season Round 14: Italian Grand Prix - Race,
  2021 Season Round 15: Russian Grand Prix - Race,
  2021 Season Round 16: Turkish Grand Prix - Race,
  2021 Season Round 17: United States Grand Prix - Race,
  2021 Season Round 18: Mexico City Grand Prix - Race,
  2021 Season Round 19: São Paulo Grand Prix - Race,
  2021 Season Round 20: Qatar Grand Prix - Race,
  2021 Season Round 21: Saudi Arabian Grand Prix - Race,
  2021 Season Round 22: Abu Dhabi Grand Prix - Race],
 2022: [2022 Season Round 1: Bahrain Grand Prix - Race,
  2022 Season Round 2: Saudi Arabian Grand Prix - Race,
  2022 Season Round 3: Australian Grand Prix - Race,
  2022 Season Round 4: Emilia Romagna Grand Prix - Race,
  2022 Season Round 5: Miami Grand Prix - Race,
  2022 Season Round 6: Spanish Grand Prix - Race,
  2022 Season Round 7: Monaco Grand Prix - Race,
  2022 Season Round 8: Azerbaijan Grand Prix - Race,
  2022 Season Round 9: Canadian Grand Prix - Race,
  2022 Season Round 10: British Grand Prix - Race,
  2022 Season Round 11: Austrian Grand Prix - Race,
  2022 Season Round 12: French Grand Prix - Race,
  2022 Season Round 13: Hungarian Grand Prix - Race,
  2022 Season Round 14: Belgian Grand Prix - Race,
  2022 Season Round 15: Dutch Grand Prix - Race,
  2022 Season Round 16: Italian Grand Prix - Race,
  2022 Season Round 17: Singapore Grand Prix - Race,
  2022 Season Round 18: Japanese Grand Prix - Race,
  2022 Season Round 19: United States Grand Prix - Race,
  2022 Season Round 20: Mexico City Grand Prix - Race,
  2022 Season Round 21: São Paulo Grand Prix - Race,
  2022 Season Round 22: Abu Dhabi Grand Prix - Race],
 2023: [2023 Season Round 1: Bahrain Grand Prix - Race,
  2023 Season Round 2: Saudi Arabian Grand Prix - Race,
  2023 Season Round 3: Australian Grand Prix - Race,
  2023 Season Round 4: Azerbaijan Grand Prix - Race,
  2023 Season Round 5: Miami Grand Prix - Race,
  2023 Season Round 6: Monaco Grand Prix - Race,
  2023 Season Round 7: Spanish Grand Prix - Race,
  2023 Season Round 8: Canadian Grand Prix - Race,
  2023 Season Round 9: Austrian Grand Prix - Race,
  2023 Season Round 10: British Grand Prix - Race,
  2023 Season Round 11: Hungarian Grand Prix - Race,
  2023 Season Round 12: Belgian Grand Prix - Race,
  2023 Season Round 13: Dutch Grand Prix - Race,
  2023 Season Round 14: Italian Grand Prix - Race,
  2023 Season Round 15: Singapore Grand Prix - Race,
  2023 Season Round 16: Japanese Grand Prix - Race,
  2023 Season Round 17: Qatar Grand Prix - Race,
  2023 Season Round 18: United States Grand Prix - Race,
  2023 Season Round 19: Mexico City Grand Prix - Race,
  2023 Season Round 20: São Paulo Grand Prix - Race,
  2023 Season Round 21: Las Vegas Grand Prix - Race,
  2023 Season Round 22: Abu Dhabi Grand Prix - Race],
 2024: [2024 Season Round 1: Bahrain Grand Prix - Race,
  2024 Season Round 2: Saudi Arabian Grand Prix - Race,
  2024 Season Round 3: Australian Grand Prix - Race,
  2024 Season Round 4: Japanese Grand Prix - Race,
  2024 Season Round 5: Chinese Grand Prix - Race,
  2024 Season Round 6: Miami Grand Prix - Race,
  2024 Season Round 7: Emilia Romagna Grand Prix - Race,
  2024 Season Round 8: Monaco Grand Prix - Race,
  2024 Season Round 9: Canadian Grand Prix - Race,
  2024 Season Round 10: Spanish Grand Prix - Race,
  2024 Season Round 11: Austrian Grand Prix - Race,
  2024 Season Round 12: British Grand Prix - Race,
  2024 Season Round 13: Hungarian Grand Prix - Race,
  2024 Season Round 14: Belgian Grand Prix - Race,
  2024 Season Round 15: Dutch Grand Prix - Race,
  2024 Season Round 16: Italian Grand Prix - Race,
  2024 Season Round 17: Azerbaijan Grand Prix - Race,
  2024 Season Round 18: Singapore Grand Prix - Race,
  2024 Season Round 19: United States Grand Prix - Race,
  2024 Season Round 20: Mexico City Grand Prix - Race,
  2024 Season Round 21: São Paulo Grand Prix - Race,
  2024 Season Round 22: Las Vegas Grand Prix - Race,
  2024 Season Round 23: Qatar Grand Prix - Race,
  2024 Season Round 24: Abu Dhabi Grand Prix - Race],
 2025: [2025 Season Round 1: Australian Grand Prix - Race,
  2025 Season Round 2: Chinese Grand Prix - Race,
  2025 Season Round 3: Japanese Grand Prix - Race,
  2025 Season Round 4: Bahrain Grand Prix - Race,
  2025 Season Round 5: Saudi Arabian Grand Prix - Race,
  2025 Season Round 6: Miami Grand Prix - Race,
  2025 Season Round 7: Emilia Romagna Grand Prix - Race,
  2025 Season Round 8: Monaco Grand Prix - Race,
  2025 Season Round 9: Spanish Grand Prix - Race,
  2025 Season Round 10: Canadian Grand Prix - Race,
  2025 Season Round 11: Austrian Grand Prix - Race,
  2025 Season Round 12: British Grand Prix - Race,
  2025 Season Round 13: Belgian Grand Prix - Race,
  2025 Season Round 14: Hungarian Grand Prix - Race,
  2025 Season Round 15: Dutch Grand Prix - Race,
  2025 Season Round 16: Italian Grand Prix - Race,
  2025 Season Round 17: Azerbaijan Grand Prix - Race,
  2025 Season Round 18: Singapore Grand Prix - Race,
  2025 Season Round 19: United States Grand Prix - Race,
  2025 Season Round 20: Mexico City Grand Prix - Race,
  2025 Season Round 21: São Paulo Grand Prix - Race,
  2025 Season Round 22: Las Vegas Grand Prix - Race,
  2025 Season Round 23: Qatar Grand Prix - Race,
  2025 Season Round 24: Abu Dhabi Grand Prix - Race]}

In [3]:
driver_mapping = io_fastf1.build_drivers_dict(sessions)
driver_mapping

{'VET': {'index': 21},
 'STR': {'index': 19},
 'VER': {'index': 19},
 'HAM': {'index': 19},
 'NOR': {'index': 19},
 'PER': {'index': 23},
 'LEC': {'index': 19},
 'RAI': {'index': 21},
 'MAZ': {'index': 21},
 'MSC': {'index': 21},
 'ALO': {'index': 19},
 'LAT': {'index': 21},
 'GAS': {'index': 19},
 'OCO': {'index': 19},
 'BOT': {'index': 23},
 'GIO': {'index': 21},
 'RIC': {'index': 17},
 'TSU': {'index': 19},
 'RUS': {'index': 19},
 'SAI': {'index': 19},
 'KUB': {'index': 13},
 'ZHO': {'index': 23},
 'ALB': {'index': 19},
 'MAG': {'index': 23},
 'HUL': {'index': 19},
 'DEV': {'index': 9},
 'SAR': {'index': 14},
 'PIA': {'index': 19},
 'LAW': {'index': 19},
 'BEA': {'index': 19},
 'COL': {'index': 19},
 'DOO': {'index': 5},
 'HAD': {'index': 19},
 'ANT': {'index': 19},
 'BOR': {'index': 19}}

# Prepare raceonly, qulionly and qualirace DataFrames

In [18]:
df_raceonly, df_qualionly, df_qualirace = io_fastf1.aggregate_driver_race__quali_results(sessions, driver_mapping)

In [19]:
df_raceonly

,Abbreviation,Bahrain Grand Prix_2021_Position,Emilia Romagna Grand Prix_2021_Position,Portuguese Grand Prix_2021_Position,Spanish Grand Prix_2021_Position,Monaco Grand Prix_2021_Position,Azerbaijan Grand Prix_2021_Position,French Grand Prix_2021_Position,Styrian Grand Prix_2021_Position,Austrian Grand Prix_2021_Position,...,Dutch Grand Prix_2025_Position,Italian Grand Prix_2025_Position,Azerbaijan Grand Prix_2025_Position,Singapore Grand Prix_2025_Position,United States Grand Prix_2025_Position,Mexico City Grand Prix_2025_Position,São Paulo Grand Prix_2025_Position,Las Vegas Grand Prix_2025_Position,Qatar Grand Prix_2025_Position,Abu Dhabi Grand Prix_2025_Position
0,NOR,4.0,3.0,5.0,8.0,3.0,5.0,5.0,5.0,3.0,...,18.0,2.0,7.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN
1,BOT,3.0,18.0,3.0,3.0,19.0,12.0,4.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PER,5.0,11.0,4.0,5.0,4.0,1.0,3.0,4.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MSC,16.0,16.0,17.0,18.0,18.0,13.0,19.0,16.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VER,2.0,1.0,2.0,2.0,1.0,18.0,1.0,1.0,1.0,...,2.0,1.0,1.0,2.0,1.0,3.0,NaN,NaN,NaN,NaN
5,GIO,12.0,14.0,12.0,15.0,10.0,11.0,15.0,15.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,RAI,11.0,13.0,20.0,12.0,11.0,10.0,17.0,11.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ALO,19.0,10.0,8.0,17.0,13.0,6.0,8.0,9.0,10.0,...,8.0,19.0,15.0,7.0,10.0,18.0,NaN,NaN,NaN,NaN
8,VET,15.0,15.0,13.0,13.0,5.0,2.0,9.0,12.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,OCO,13.0,9.0,7.0,9.0,9.0,20.0,14.0,14.0,20.0,...,10.0,15.0,14.0,18.0,15.0,9.0,NaN,NaN,NaN,NaN
10,TSU,9.0,12.0,15.0,20.0,16.0,7.0,13.0,10.0,12.0,...,9.0,13.0,6.0,12.0,7.0,11.0,NaN,NaN,NaN,NaN
11,RIC,7.0,6.0,9.0,6.0,12.0,9.0,6.0,13.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,HAM,1.0,2.0,1.0,1.0,7.0,15.0,2.0,2.0,4.0,...,20.0,6.0,8.0,8.0,4.0,8.0,NaN,NaN,NaN,NaN
13,LAT,18.0,20.0,18.0,16.0,15.0,16.0,18.0,17.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,STR,10.0,8.0,14.0,11.0,8.0,19.0,10.0,8.0,13.0,...,7.0,18.0,17.0,13.0,12.0,14.0,NaN,NaN,NaN,NaN
15,SAI,8.0,5.0,11.0,7.0,2.0,8.0,11.0,6.0,5.0,...,13.0,11.0,3.0,10.0,20.0,17.0,NaN,NaN,NaN,NaN
16,LEC,6.0,4.0,6.0,4.0,20.0,4.0,16.0,7.0,8.0,...,19.0,4.0,9.0,6.0,3.0,2.0,NaN,NaN,NaN,NaN
17,GAS,17.0,7.0,10.0,10.0,6.0,3.0,7.0,20.0,9.0,...,17.0,16.0,18.0,19.0,19.0,15.0,NaN,NaN,NaN,NaN
18,RUS,14.0,19.0,16.0,14.0,14.0,17.0,12.0,19.0,11.0,...,4.0,5.0,2.0,1.0,6.0,7.0,NaN,NaN,NaN,NaN
19,MAZ,20.0,17.0,19.0,19.0,17.0,14.0,20.0,18.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,KUB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ZHO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,7.0,13.0,14.0,14.0,12.0,NaN,NaN,NaN,NaN
24,HUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.0,20.0,16.0,20.0,8.0,19.0,NaN,NaN,NaN,NaN
25,DEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,SAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,PIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,20.0,4.0,5.0,5.0,NaN,NaN,NaN,NaN
28,LAW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,14.0,5.0,15.0,11.0,20.0,NaN,NaN,NaN,NaN
29,BEA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,12.0,12.0,9.0,9.0,4.0,NaN,NaN,NaN,NaN
30,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,17.0,19.0,16.0,17.0,16.0,NaN,NaN,NaN,NaN
31,DOO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,HAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,10.0,10.0,11.0,16.0,13.0,NaN,NaN,NaN,NaN
33,ANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,9.0,4.0,5.0,13.0,6.0,NaN,NaN,NaN,NaN
34,BOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.0,8.0,11.0,17.0,18.0,10.0,NaN,NaN,NaN,NaN

In [20]:
df_qualionly

,Abbreviation,Bahrain Grand Prix_2021_GridPosition,Emilia Romagna Grand Prix_2021_GridPosition,Portuguese Grand Prix_2021_GridPosition,Spanish Grand Prix_2021_GridPosition,Monaco Grand Prix_2021_GridPosition,Azerbaijan Grand Prix_2021_GridPosition,French Grand Prix_2021_GridPosition,Styrian Grand Prix_2021_GridPosition,Austrian Grand Prix_2021_GridPosition,...,Dutch Grand Prix_2025_GridPosition,Italian Grand Prix_2025_GridPosition,Azerbaijan Grand Prix_2025_GridPosition,Singapore Grand Prix_2025_GridPosition,United States Grand Prix_2025_GridPosition,Mexico City Grand Prix_2025_GridPosition,São Paulo Grand Prix_2025_GridPosition,Las Vegas Grand Prix_2025_GridPosition,Qatar Grand Prix_2025_GridPosition,Abu Dhabi Grand Prix_2025_GridPosition
0,NOR,7.0,7.0,7.0,9.0,5.0,9.0,8.0,3.0,2.0,...,2.0,2.0,7.0,5.0,2.0,1.0,NaN,NaN,NaN,NaN
1,BOT,3.0,8.0,1.0,3.0,3.0,10.0,3.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PER,0.0,2.0,4.0,8.0,9.0,6.0,4.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MSC,18.0,18.0,19.0,18.0,20.0,17.0,15.0,19.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VER,1.0,3.0,3.0,2.0,2.0,3.0,1.0,1.0,1.0,...,3.0,1.0,1.0,2.0,1.0,5.0,NaN,NaN,NaN,NaN
5,GIO,12.0,17.0,12.0,14.0,10.0,20.0,13.0,15.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,RAI,14.0,16.0,15.0,17.0,14.0,14.0,17.0,18.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ALO,9.0,15.0,13.0,10.0,17.0,8.0,9.0,8.0,14.0,...,10.0,8.0,11.0,10.0,10.0,14.0,NaN,NaN,NaN,NaN
8,VET,20.0,0.0,10.0,13.0,8.0,11.0,12.0,14.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,OCO,16.0,9.0,6.0,5.0,11.0,12.0,11.0,17.0,17.0,...,18.0,15.0,20.0,17.0,17.0,11.0,NaN,NaN,NaN,NaN
10,TSU,13.0,20.0,14.0,16.0,16.0,7.0,0.0,11.0,7.0,...,12.0,9.0,6.0,13.0,13.0,10.0,NaN,NaN,NaN,NaN
11,RIC,6.0,6.0,16.0,7.0,12.0,13.0,10.0,13.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,HAM,2.0,1.0,2.0,1.0,7.0,2.0,2.0,2.0,4.0,...,7.0,10.0,12.0,6.0,5.0,3.0,NaN,NaN,NaN,NaN
13,LAT,17.0,14.0,18.0,19.0,18.0,16.0,16.0,16.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,STR,10.0,10.0,17.0,11.0,13.0,19.0,19.0,9.0,9.0,...,19.0,16.0,14.0,15.0,19.0,19.0,NaN,NaN,NaN,NaN
15,SAI,8.0,11.0,5.0,6.0,4.0,5.0,5.0,12.0,10.0,...,9.0,13.0,2.0,18.0,9.0,12.0,NaN,NaN,NaN,NaN
16,LEC,4.0,4.0,8.0,4.0,1.0,1.0,7.0,7.0,12.0,...,6.0,4.0,10.0,7.0,3.0,2.0,NaN,NaN,NaN,NaN
17,GAS,5.0,5.0,9.0,12.0,6.0,4.0,6.0,6.0,6.0,...,14.0,20.0,18.0,19.0,14.0,18.0,NaN,NaN,NaN,NaN
18,RUS,15.0,12.0,11.0,15.0,15.0,15.0,14.0,10.0,8.0,...,5.0,5.0,5.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN
19,MAZ,19.0,19.0,20.0,20.0,19.0,18.0,18.0,20.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,KUB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ZHO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.0,14.0,19.0,20.0,18.0,17.0,NaN,NaN,NaN,NaN
24,HUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.0,12.0,17.0,11.0,11.0,13.0,NaN,NaN,NaN,NaN
25,DEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,SAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,PIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,9.0,3.0,6.0,7.0,NaN,NaN,NaN,NaN
28,LAW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,18.0,3.0,12.0,12.0,15.0,NaN,NaN,NaN,NaN
29,BEA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,11.0,15.0,9.0,8.0,9.0,NaN,NaN,NaN,NaN
30,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,17.0,16.0,16.0,15.0,20.0,NaN,NaN,NaN,NaN
31,DOO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,HAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,19.0,8.0,8.0,20.0,8.0,NaN,NaN,NaN,NaN
33,ANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,6.0,4.0,4.0,7.0,6.0,NaN,NaN,NaN,NaN
34,BOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.0,7.0,13.0,14.0,16.0,16.0,NaN,NaN,NaN,NaN

In [21]:
df_qualirace

,Abbreviation,Bahrain Grand Prix_2021_GridPosition,Bahrain Grand Prix_2021_Position,Emilia Romagna Grand Prix_2021_GridPosition,Emilia Romagna Grand Prix_2021_Position,Portuguese Grand Prix_2021_GridPosition,Portuguese Grand Prix_2021_Position,Spanish Grand Prix_2021_GridPosition,Spanish Grand Prix_2021_Position,Monaco Grand Prix_2021_GridPosition,...,Mexico City Grand Prix_2025_GridPosition,Mexico City Grand Prix_2025_Position,São Paulo Grand Prix_2025_GridPosition,São Paulo Grand Prix_2025_Position,Las Vegas Grand Prix_2025_GridPosition,Las Vegas Grand Prix_2025_Position,Qatar Grand Prix_2025_GridPosition,Qatar Grand Prix_2025_Position,Abu Dhabi Grand Prix_2025_GridPosition,Abu Dhabi Grand Prix_2025_Position
0,NOR,7.0,4.0,7.0,3.0,7.0,5.0,9.0,8.0,5.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BOT,3.0,3.0,8.0,18.0,1.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PER,0.0,5.0,2.0,11.0,4.0,4.0,8.0,5.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MSC,18.0,16.0,18.0,16.0,19.0,17.0,18.0,18.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VER,1.0,2.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,...,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,GIO,12.0,12.0,17.0,14.0,12.0,12.0,14.0,15.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,RAI,14.0,11.0,16.0,13.0,15.0,20.0,17.0,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ALO,9.0,19.0,15.0,10.0,13.0,8.0,10.0,17.0,17.0,...,14.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,VET,20.0,15.0,0.0,15.0,10.0,13.0,13.0,13.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,OCO,16.0,13.0,9.0,9.0,6.0,7.0,5.0,9.0,11.0,...,11.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,TSU,13.0,9.0,20.0,12.0,14.0,15.0,16.0,20.0,16.0,...,10.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,RIC,6.0,7.0,6.0,6.0,16.0,9.0,7.0,6.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,HAM,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,7.0,...,3.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,LAT,17.0,18.0,14.0,20.0,18.0,18.0,19.0,16.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,STR,10.0,10.0,10.0,8.0,17.0,14.0,11.0,11.0,13.0,...,19.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,SAI,8.0,8.0,11.0,5.0,5.0,11.0,6.0,7.0,4.0,...,12.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,LEC,4.0,6.0,4.0,4.0,8.0,6.0,4.0,4.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,GAS,5.0,17.0,5.0,7.0,9.0,10.0,12.0,10.0,6.0,...,18.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,RUS,15.0,14.0,12.0,19.0,11.0,16.0,15.0,14.0,15.0,...,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,MAZ,19.0,20.0,19.0,17.0,20.0,19.0,20.0,19.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,KUB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ZHO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,HUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,DEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,SAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,PIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,LAW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,BEA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,DOO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,HAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,ANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,BOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_raceonly[df_raceonly.isin([0])].dropna()

Empty DataFrame
Columns: [Abbreviation, Bahrain Grand Prix_2021_Position, Emilia Romagna Grand Prix_2021_Position, Portuguese Grand Prix_2021_Position, Spanish Grand Prix_2021_Position, Monaco Grand Prix_2021_Position, Azerbaijan Grand Prix_2021_Position, French Grand Prix_2021_Position, Styrian Grand Prix_2021_Position, Austrian Grand Prix_2021_Position, British Grand Prix_2021_Position, Hungarian Grand Prix_2021_Position, Belgian Grand Prix_2021_Position, Dutch Grand Prix_2021_Position, Italian Grand Prix_2021_Position, Russian Grand Prix_2021_Position, Turkish Grand Prix_2021_Position, United States Grand Prix_2021_Position, Mexico City Grand Prix_2021_Position, São Paulo Grand Prix_2021_Position, Qatar Grand Prix_2021_Position, Saudi Arabian Grand Prix_2021_Position, Abu Dhabi Grand Prix_2021_Position, Bahrain Grand Prix_2022_Position, Saudi Arabian Grand Prix_2022_Position, Australian Grand Prix_2022_Position, Emilia Romagna Grand Prix_2022_Position, Miami Grand Prix_2022_Position, Spanish Grand Prix_2022_Position, Monaco Grand Prix_2022_Position, Azerbaijan Grand Prix_2022_Position, Canadian Grand Prix_2022_Position, British Grand Prix_2022_Position, Austrian Grand Prix_2022_Position, French Grand Prix_2022_Position, Hungarian Grand Prix_2022_Position, Belgian Grand Prix_2022_Position, Dutch Grand Prix_2022_Position, Italian Grand Prix_2022_Position, Singapore Grand Prix_2022_Position, Japanese Grand Prix_2022_Position, United States Grand Prix_2022_Position, Mexico City Grand Prix_2022_Position, São Paulo Grand Prix_2022_Position, Abu Dhabi Grand Prix_2022_Position, Bahrain Grand Prix_2023_Position, Saudi Arabian Grand Prix_2023_Position, Australian Grand Prix_2023_Position, Azerbaijan Grand Prix_2023_Position, Miami Grand Prix_2023_Position, Monaco Grand Prix_2023_Position, Spanish Grand Prix_2023_Position, Canadian Grand Prix_2023_Position, Austrian Grand Prix_2023_Position, British Grand Prix_2023_Position, Hungarian Grand Prix_2023_Position, Belgian Grand Prix_2023_Position, Dutch Grand Prix_2023_Position, Italian Grand Prix_2023_Position, Singapore Grand Prix_2023_Position, Japanese Grand Prix_2023_Position, Qatar Grand Prix_2023_Position, United States Grand Prix_2023_Position, Mexico City Grand Prix_2023_Position, São Paulo Grand Prix_2023_Position, Las Vegas Grand Prix_2023_Position, Abu Dhabi Grand Prix_2023_Position, Bahrain Grand Prix_2024_Position, Saudi Arabian Grand Prix_2024_Position, Australian Grand Prix_2024_Position, Japanese Grand Prix_2024_Position, Chinese Grand Prix_2024_Position, Miami Grand Prix_2024_Position, Emilia Romagna Grand Prix_2024_Position, Monaco Grand Prix_2024_Position, Canadian Grand Prix_2024_Position, Spanish Grand Prix_2024_Position, Austrian Grand Prix_2024_Position, British Grand Prix_2024_Position, Hungarian Grand Prix_2024_Position, Belgian Grand Prix_2024_Position, Dutch Grand Prix_2024_Position, Italian Grand Prix_2024_Position, Azerbaijan Grand Prix_2024_Position, Singapore Grand Prix_2024_Position, United States Grand Prix_2024_Position, Mexico City Grand Prix_2024_Position, São Paulo Grand Prix_2024_Position, Las Vegas Grand Prix_2024_Position, Qatar Grand Prix_2024_Position, Abu Dhabi Grand Prix_2024_Position, Australian Grand Prix_2025_Position, Chinese Grand Prix_2025_Position, Japanese Grand Prix_2025_Position, Bahrain Grand Prix_2025_Position, Saudi Arabian Grand Prix_2025_Position, Miami Grand Prix_2025_Position, Emilia Romagna Grand Prix_2025_Position, Monaco Grand Prix_2025_Position, Spanish Grand Prix_2025_Position, ...]
Index: []

[0 rows x 115 columns]

In [9]:
df_qualionly[df_qualionly.isin([0])].dropna()

Empty DataFrame
Columns: [Abbreviation, Bahrain Grand Prix_2021_GridPosition, Emilia Romagna Grand Prix_2021_GridPosition, Portuguese Grand Prix_2021_GridPosition, Spanish Grand Prix_2021_GridPosition, Monaco Grand Prix_2021_GridPosition, Azerbaijan Grand Prix_2021_GridPosition, French Grand Prix_2021_GridPosition, Styrian Grand Prix_2021_GridPosition, Austrian Grand Prix_2021_GridPosition, British Grand Prix_2021_GridPosition, Hungarian Grand Prix_2021_GridPosition, Belgian Grand Prix_2021_GridPosition, Dutch Grand Prix_2021_GridPosition, Italian Grand Prix_2021_GridPosition, Russian Grand Prix_2021_GridPosition, Turkish Grand Prix_2021_GridPosition, United States Grand Prix_2021_GridPosition, Mexico City Grand Prix_2021_GridPosition, São Paulo Grand Prix_2021_GridPosition, Qatar Grand Prix_2021_GridPosition, Saudi Arabian Grand Prix_2021_GridPosition, Abu Dhabi Grand Prix_2021_GridPosition, Bahrain Grand Prix_2022_GridPosition, Saudi Arabian Grand Prix_2022_GridPosition, Australian Grand Prix_2022_GridPosition, Emilia Romagna Grand Prix_2022_GridPosition, Miami Grand Prix_2022_GridPosition, Spanish Grand Prix_2022_GridPosition, Monaco Grand Prix_2022_GridPosition, Azerbaijan Grand Prix_2022_GridPosition, Canadian Grand Prix_2022_GridPosition, British Grand Prix_2022_GridPosition, Austrian Grand Prix_2022_GridPosition, French Grand Prix_2022_GridPosition, Hungarian Grand Prix_2022_GridPosition, Belgian Grand Prix_2022_GridPosition, Dutch Grand Prix_2022_GridPosition, Italian Grand Prix_2022_GridPosition, Singapore Grand Prix_2022_GridPosition, Japanese Grand Prix_2022_GridPosition, United States Grand Prix_2022_GridPosition, Mexico City Grand Prix_2022_GridPosition, São Paulo Grand Prix_2022_GridPosition, Abu Dhabi Grand Prix_2022_GridPosition, Bahrain Grand Prix_2023_GridPosition, Saudi Arabian Grand Prix_2023_GridPosition, Australian Grand Prix_2023_GridPosition, Azerbaijan Grand Prix_2023_GridPosition, Miami Grand Prix_2023_GridPosition, Monaco Grand Prix_2023_GridPosition, Spanish Grand Prix_2023_GridPosition, Canadian Grand Prix_2023_GridPosition, Austrian Grand Prix_2023_GridPosition, British Grand Prix_2023_GridPosition, Hungarian Grand Prix_2023_GridPosition, Belgian Grand Prix_2023_GridPosition, Dutch Grand Prix_2023_GridPosition, Italian Grand Prix_2023_GridPosition, Singapore Grand Prix_2023_GridPosition, Japanese Grand Prix_2023_GridPosition, Qatar Grand Prix_2023_GridPosition, United States Grand Prix_2023_GridPosition, Mexico City Grand Prix_2023_GridPosition, São Paulo Grand Prix_2023_GridPosition, Las Vegas Grand Prix_2023_GridPosition, Abu Dhabi Grand Prix_2023_GridPosition, Bahrain Grand Prix_2024_GridPosition, Saudi Arabian Grand Prix_2024_GridPosition, Australian Grand Prix_2024_GridPosition, Japanese Grand Prix_2024_GridPosition, Chinese Grand Prix_2024_GridPosition, Miami Grand Prix_2024_GridPosition, Emilia Romagna Grand Prix_2024_GridPosition, Monaco Grand Prix_2024_GridPosition, Canadian Grand Prix_2024_GridPosition, Spanish Grand Prix_2024_GridPosition, Austrian Grand Prix_2024_GridPosition, British Grand Prix_2024_GridPosition, Hungarian Grand Prix_2024_GridPosition, Belgian Grand Prix_2024_GridPosition, Dutch Grand Prix_2024_GridPosition, Italian Grand Prix_2024_GridPosition, Azerbaijan Grand Prix_2024_GridPosition, Singapore Grand Prix_2024_GridPosition, United States Grand Prix_2024_GridPosition, Mexico City Grand Prix_2024_GridPosition, São Paulo Grand Prix_2024_GridPosition, Las Vegas Grand Prix_2024_GridPosition, Qatar Grand Prix_2024_GridPosition, Abu Dhabi Grand Prix_2024_GridPosition, Australian Grand Prix_2025_GridPosition, Chinese Grand Prix_2025_GridPosition, Japanese Grand Prix_2025_GridPosition, Bahrain Grand Prix_2025_GridPosition, Saudi Arabian Grand Prix_2025_GridPosition, Miami Grand Prix_2025_GridPosition, Emilia Romagna Grand Prix_2025_GridPosition, Monaco Grand Prix_2025_GridPosition, Spanish Grand Prix_2025_GridPosition, ...]
Index: []

[0 rows x 115 columns]

In [10]:
df_qualirace[df_qualirace.isin([0])].dropna()

Empty DataFrame
Columns: [Abbreviation, Bahrain Grand Prix_2021_GridPosition, Bahrain Grand Prix_2021_Position, Emilia Romagna Grand Prix_2021_GridPosition, Emilia Romagna Grand Prix_2021_Position, Portuguese Grand Prix_2021_GridPosition, Portuguese Grand Prix_2021_Position, Spanish Grand Prix_2021_GridPosition, Spanish Grand Prix_2021_Position, Monaco Grand Prix_2021_GridPosition, Monaco Grand Prix_2021_Position, Azerbaijan Grand Prix_2021_GridPosition, Azerbaijan Grand Prix_2021_Position, French Grand Prix_2021_GridPosition, French Grand Prix_2021_Position, Styrian Grand Prix_2021_GridPosition, Styrian Grand Prix_2021_Position, Austrian Grand Prix_2021_GridPosition, Austrian Grand Prix_2021_Position, British Grand Prix_2021_GridPosition, British Grand Prix_2021_Position, Hungarian Grand Prix_2021_GridPosition, Hungarian Grand Prix_2021_Position, Belgian Grand Prix_2021_GridPosition, Belgian Grand Prix_2021_Position, Dutch Grand Prix_2021_GridPosition, Dutch Grand Prix_2021_Position, Italian Grand Prix_2021_GridPosition, Italian Grand Prix_2021_Position, Russian Grand Prix_2021_GridPosition, Russian Grand Prix_2021_Position, Turkish Grand Prix_2021_GridPosition, Turkish Grand Prix_2021_Position, United States Grand Prix_2021_GridPosition, United States Grand Prix_2021_Position, Mexico City Grand Prix_2021_GridPosition, Mexico City Grand Prix_2021_Position, São Paulo Grand Prix_2021_GridPosition, São Paulo Grand Prix_2021_Position, Qatar Grand Prix_2021_GridPosition, Qatar Grand Prix_2021_Position, Saudi Arabian Grand Prix_2021_GridPosition, Saudi Arabian Grand Prix_2021_Position, Abu Dhabi Grand Prix_2021_GridPosition, Abu Dhabi Grand Prix_2021_Position, Bahrain Grand Prix_2022_GridPosition, Bahrain Grand Prix_2022_Position, Saudi Arabian Grand Prix_2022_GridPosition, Saudi Arabian Grand Prix_2022_Position, Australian Grand Prix_2022_GridPosition, Australian Grand Prix_2022_Position, Emilia Romagna Grand Prix_2022_GridPosition, Emilia Romagna Grand Prix_2022_Position, Miami Grand Prix_2022_GridPosition, Miami Grand Prix_2022_Position, Spanish Grand Prix_2022_GridPosition, Spanish Grand Prix_2022_Position, Monaco Grand Prix_2022_GridPosition, Monaco Grand Prix_2022_Position, Azerbaijan Grand Prix_2022_GridPosition, Azerbaijan Grand Prix_2022_Position, Canadian Grand Prix_2022_GridPosition, Canadian Grand Prix_2022_Position, British Grand Prix_2022_GridPosition, British Grand Prix_2022_Position, Austrian Grand Prix_2022_GridPosition, Austrian Grand Prix_2022_Position, French Grand Prix_2022_GridPosition, French Grand Prix_2022_Position, Hungarian Grand Prix_2022_GridPosition, Hungarian Grand Prix_2022_Position, Belgian Grand Prix_2022_GridPosition, Belgian Grand Prix_2022_Position, Dutch Grand Prix_2022_GridPosition, Dutch Grand Prix_2022_Position, Italian Grand Prix_2022_GridPosition, Italian Grand Prix_2022_Position, Singapore Grand Prix_2022_GridPosition, Singapore Grand Prix_2022_Position, Japanese Grand Prix_2022_GridPosition, Japanese Grand Prix_2022_Position, United States Grand Prix_2022_GridPosition, United States Grand Prix_2022_Position, Mexico City Grand Prix_2022_GridPosition, Mexico City Grand Prix_2022_Position, São Paulo Grand Prix_2022_GridPosition, São Paulo Grand Prix_2022_Position, Abu Dhabi Grand Prix_2022_GridPosition, Abu Dhabi Grand Prix_2022_Position, Bahrain Grand Prix_2023_GridPosition, Bahrain Grand Prix_2023_Position, Saudi Arabian Grand Prix_2023_GridPosition, Saudi Arabian Grand Prix_2023_Position, Australian Grand Prix_2023_GridPosition, Australian Grand Prix_2023_Position, Azerbaijan Grand Prix_2023_GridPosition, Azerbaijan Grand Prix_2023_Position, Miami Grand Prix_2023_GridPosition, Miami Grand Prix_2023_Position, Monaco Grand Prix_2023_GridPosition, ...]
Index: []

[0 rows x 229 columns]

# Save Interim raceonly, qualionly and qualirace data

In [23]:
df_raceonly.to_csv(config.FASTF1_DATA_DIR / "interim" / "df_raceonly.csv", index=False)
df_qualionly.to_csv(config.FASTF1_DATA_DIR / "interim" / "df_qualionly.csv", index=False)
df_qualirace.to_csv(config.FASTF1_DATA_DIR / "interim" / "df_qualirace.csv", index=False)

# Load Interim raceonly, qualionly and qualirace data

In [4]:
df_raceonly = pd.read_csv(config.FASTF1_DATA_DIR / "interim" / "df_raceonly.csv")
df_qualionly = pd.read_csv(config.FASTF1_DATA_DIR / "interim" / "df_qualionly.csv")
df_qualirace = pd.read_csv(config.FASTF1_DATA_DIR / "interim" / "df_qualirace.csv")

# Aggregate data and create windows

In [5]:
df_windows_raceonly = io_fastf1.create_columns_windows_raceonly(df_raceonly)
df_windows_raceonly

Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_86 due to NaN at position(s) [4], jumping to window_index 90
Skipping window window_91 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 95
Skipping window window_96 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 100
Skipping window window_101 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 105
Skipping window window_106 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 110
Skipping window window_86 due to NaN at position(s) [4], jumping to window_index 90
Skipping window window_91 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 95
Skipping window window_96 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 100
Skipping window window_101 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 105
Skipping window window_106 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 110
Skipping window window_19 due to NaN at position(s) [4], jumping to window_index 23
Skipping window window_40 due to NaN at position(s) [4], jumping to window_index 44
Skipping window window_45 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 49
Skipping window window_50 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 54
Skipping window window_55 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 59
Skipping window window_60 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 64
Skipping window window_65 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 69
Skipping window window_70 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 74
Skipping window window_75 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 79
Skipping window window_80 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 84
Skipping window window_85 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 89
Skipping window window_90 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 94
Skipping window window_95 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 99
Skipping window window_100 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 104
Skipping window window_105 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 109
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_18 due to NaN at position(s) [4], jumping to window_index 22
Skipping window window_23 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 27
Skipping window window_28 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 32
Skipping window window_33 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 37
Skipping window window_38 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 42
Skipping window window_43 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 47
Skipping window window_48 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 52
Skipping window window_53 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 57
Skipping window window_58 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 62
Skipping window window_63 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 67
Skipping window window_68 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 72
Skipping window window_73 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 77
Skipping window window_78 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 82
Skipping window window_83 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 87
Skipping window window_88 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 92
Skipping window window_93 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 97
Skipping window window_98 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 102
Skipping window window_103 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 107
Skipping window window_108 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 112
Skipping window window_8 due to NaN at position(s) [4], jumping to window_index 12
Skipping window window_13 due to NaN at position(s) [0], jumping to window_index 13
Skipping window window_18 due to NaN at position(s) [4], jumping to window_index 22
Skipping window window_23 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 27
Skipping window window_28 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 32
Skipping window window_33 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 37
Skipping window window_38 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 42
Skipping window window_43 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 47
Skipping window window_48 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 52
Skipping window window_53 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 57
Skipping window window_58 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 62
Skipping window window_63 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 67
Skipping window window_68 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 72
Skipping window window_73 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 77
Skipping window window_78 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 82
Skipping window window_83 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 87
Skipping window window_88 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 92
Skipping window window_93 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 97
Skipping window window_98 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 102
Skipping window window_103 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 107
Skipping window window_108 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 112
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_18 due to NaN at position(s) [4], jumping to window_index 22
Skipping window window_23 due to NaN at position(s) [0], jumping to window_index 23
Skipping window window_40 due to NaN at position(s) [4], jumping to window_index 44
Skipping window window_45 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 49
Skipping window window_50 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 54
Skipping window window_55 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 59
Skipping window window_60 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 64
Skipping window window_65 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 69
Skipping window window_70 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 74
Skipping window window_75 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 79
Skipping window window_80 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 84
Skipping window window_85 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 89
Skipping window window_90 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 94
Skipping window window_95 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 99
Skipping window window_100 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 104
Skipping window window_105 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 109
Skipping window window_85 due to NaN at position(s) [4], jumping to window_index 89
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_40 due to NaN at position(s) [4], jumping to window_index 44
Skipping window window_45 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 49
Skipping window window_50 due to NaN at position(s) [0 1 2 3], jumping to window_index 53
Skipping window window_54 due to NaN at position(s) [2 3 4], jumping to window_index 58
Skipping window window_59 due to NaN at position(s) [0 1], jumping to window_index 60
Skipping window window_80 due to NaN at position(s) [4], jumping to window_index 84
Skipping window window_85 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 89
Skipping window window_90 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 94
Skipping window window_95 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 99
Skipping window window_100 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 104
Skipping window window_105 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 109
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_40 due to NaN at position(s) [4], jumping to window_index 44
Skipping window window_45 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 49
Skipping window window_50 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 54
Skipping window window_55 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 59
Skipping window window_60 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 64
Skipping window window_65 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 69
Skipping window window_70 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 74
Skipping window window_75 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 79
Skipping window window_80 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 84
Skipping window window_85 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 89
Skipping window window_90 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 94
Skipping window window_95 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 99
Skipping window window_100 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 104
Skipping window window_105 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 109
Skipping window window_54 due to NaN at position(s) [4], jumping to window_index 58
Skipping window window_94 due to NaN at position(s) [4], jumping to window_index 98
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_63 due to NaN at position(s) [4], jumping to window_index 67
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_17 due to NaN at position(s) [4], jumping to window_index 21
Skipping window window_22 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 26
Skipping window window_27 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 31
Skipping window window_32 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 36
Skipping window window_37 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 41
Skipping window window_42 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 46
Skipping window window_47 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 51
Skipping window window_52 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 56
Skipping window window_57 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 61
Skipping window window_62 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 66
Skipping window window_67 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 71
Skipping window window_72 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 76
Skipping window window_77 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 81
Skipping window window_82 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 86
Skipping window window_87 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 91
Skipping window window_92 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 96
Skipping window window_97 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 101
Skipping window window_102 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 106
Skipping window window_107 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 111
Skipping window window_0 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 4
Skipping window window_5 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 9
Skipping window window_10 due to NaN at position(s) [0 1 4], jumping to window_index 14
Skipping window window_15 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 19
Skipping window window_20 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 24
Skipping window window_25 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 29
Skipping window window_30 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 34
Skipping window window_35 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 39
Skipping window window_40 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 44
Skipping window window_45 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 49
Skipping window window_50 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 54
Skipping window window_55 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 59
Skipping window window_60 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 64
Skipping window window_65 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 69
Skipping window window_70 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 74
Skipping window window_75 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 79
Skipping window window_80 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 84
Skipping window window_85 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 89
Skipping window window_90 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 94
Skipping window window_95 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 99
Skipping window window_100 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 104
Skipping window window_105 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 109
Skipping window window_0 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 4
Skipping window window_5 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 9
Skipping window window_10 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 14
Skipping window window_15 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 19
Skipping window window_20 due to NaN at position(s) [0 1], jumping to window_index 21
Skipping window window_78 due to NaN at position(s) [4], jumping to window_index 82
Skipping window window_83 due to NaN at position(s) [3], jumping to window_index 86
Skipping window window_87 due to NaN at position(s) [3 4], jumping to window_index 91
Skipping window window_92 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 96
Skipping window window_97 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 101
Skipping window window_102 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 106
Skipping window window_107 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 111
Skipping window window_0 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 4
Skipping window window_5 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 9
Skipping window window_10 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 14
Skipping window window_15 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 19
Skipping window window_20 due to NaN at position(s) [0 1], jumping to window_index 21
Skipping window window_86 due to NaN at position(s) [4], jumping to window_index 90
Skipping window window_91 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 95
Skipping window window_96 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 100
Skipping window window_101 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 105
Skipping window window_106 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 110
Skipping window window_0 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 4
Skipping window window_5 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 9
Skipping window window_10 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 14
Skipping window window_15 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 19
Skipping window window_20 due to NaN at position(s) [0 1], jumping to window_index 21
Skipping window window_33 due to NaN at position(s) [4], jumping to window_index 37
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_0 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 4
Skipping window window_5 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 9
Skipping window window_10 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 14
Skipping window window_15 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 19
Skipping window window_20 due to NaN at position(s) [0 1 4], jumping to window_index 24
Skipping window window_25 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 29
Skipping window window_30 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 34
Skipping window window_35 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 39
Skipping window window_40 due to NaN at position(s) [0 1 2 3], jumping to window_index 43
Skipping window window_106 due to NaN at position(s) [4], jumping to window_index 110
Skipping window window_0 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 4
Skipping window window_5 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 9
Skipping window window_10 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 14
Skipping window window_15 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 19
Skipping window window_20 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 24
Skipping window window_25 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 29
Skipping window window_30 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 34
Skipping window window_35 due to NaN at position(s) [0 1 3 4], jumping to window_index 39
Skipping window window_40 due to NaN at position(s) [0 1 2 3], jumping to window_index 43
Skipping window window_50 due to NaN at position(s) [4], jumping to window_index 54
Skipping window window_55 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 59
Skipping window window_60 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 64
Skipping window window_65 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 69
Skipping window window_70 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 74
Skipping window window_75 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 79
Skipping window window_80 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 84
Skipping window window_85 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 89
Skipping window window_90 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 94
Skipping window window_95 due to NaN at position(s) [0 1 2 3 4], jumping to window_index 99

     race0 race1 race2 race3 race4
0      4.0   3.0   5.0   8.0   3.0
1      3.0   5.0   8.0   3.0   5.0
2      5.0   8.0   3.0   5.0   5.0
3      8.0   3.0   5.0   5.0   5.0
4      3.0   5.0   5.0   5.0   3.0
...    ...   ...   ...   ...   ...
1990  18.0   9.0   6.0  15.0   8.0
1991   9.0   6.0  15.0   8.0  11.0
1992   6.0  15.0   8.0  11.0  17.0
1993  15.0   8.0  11.0  17.0  18.0
1994   8.0  11.0  17.0  18.0  10.0

[1995 rows x 5 columns]

In [6]:
df_windows_qualirace = io_fastf1.create_columns_windows_race_quali(df_qualirace)
df_windows_qualirace

Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_86 due to NaN before position 9, jumping to window_index 95
Skipping window window_96 due to NaN before position 9, jumping to window_index 105
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_86 due to NaN before position 9, jumping to window_index 95
Skipping window window_96 due to NaN before position 9, jumping to window_index 105
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_19 due to NaN before position 9, jumping to window_index 28
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_90 due to NaN before position 9, jumping to window_index 99
Skipping window window_100 due to NaN before position 9, jumping to window_index 109
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_18 due to NaN before position 9, jumping to window_index 27
Skipping window window_28 due to NaN before position 9, jumping to window_index 37
Skipping window window_38 due to NaN before position 9, jumping to window_index 47
Skipping window window_48 due to NaN before position 9, jumping to window_index 57
Skipping window window_58 due to NaN before position 9, jumping to window_index 67
Skipping window window_68 due to NaN before position 9, jumping to window_index 77
Skipping window window_78 due to NaN before position 9, jumping to window_index 87
Skipping window window_88 due to NaN before position 9, jumping to window_index 97
Skipping window window_98 due to NaN before position 9, jumping to window_index 107
Skipping window window_108 due to NaN before position 9, jumping to window_index 117
Skipping window window_8 due to NaN before position 9, jumping to window_index 17
Skipping window window_18 due to NaN before position 9, jumping to window_index 27
Skipping window window_28 due to NaN before position 9, jumping to window_index 37
Skipping window window_38 due to NaN before position 9, jumping to window_index 47
Skipping window window_48 due to NaN before position 9, jumping to window_index 57
Skipping window window_58 due to NaN before position 9, jumping to window_index 67
Skipping window window_68 due to NaN before position 9, jumping to window_index 77
Skipping window window_78 due to NaN before position 9, jumping to window_index 87
Skipping window window_88 due to NaN before position 9, jumping to window_index 97
Skipping window window_98 due to NaN before position 9, jumping to window_index 107
Skipping window window_108 due to NaN before position 9, jumping to window_index 117
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_18 due to NaN before position 9, jumping to window_index 27
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_90 due to NaN before position 9, jumping to window_index 99
Skipping window window_100 due to NaN before position 9, jumping to window_index 109
Skipping window window_85 due to NaN before position 9, jumping to window_index 94
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 7, jumping to window_index 57
Skipping window window_58 due to NaN before position 5, jumping to window_index 63
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_90 due to NaN before position 9, jumping to window_index 99
Skipping window window_100 due to NaN before position 9, jumping to window_index 109
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_90 due to NaN before position 9, jumping to window_index 99
Skipping window window_100 due to NaN before position 9, jumping to window_index 109
Skipping window window_54 due to NaN before position 9, jumping to window_index 63
Skipping window window_94 due to NaN before position 9, jumping to window_index 103
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_63 due to NaN before position 9, jumping to window_index 72
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_17 due to NaN before position 9, jumping to window_index 26
Skipping window window_27 due to NaN before position 9, jumping to window_index 36
Skipping window window_37 due to NaN before position 9, jumping to window_index 46
Skipping window window_47 due to NaN before position 9, jumping to window_index 56
Skipping window window_57 due to NaN before position 9, jumping to window_index 66
Skipping window window_67 due to NaN before position 9, jumping to window_index 76
Skipping window window_77 due to NaN before position 9, jumping to window_index 86
Skipping window window_87 due to NaN before position 9, jumping to window_index 96
Skipping window window_97 due to NaN before position 9, jumping to window_index 106
Skipping window window_107 due to NaN before position 9, jumping to window_index 116
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_90 due to NaN before position 9, jumping to window_index 99
Skipping window window_100 due to NaN before position 9, jumping to window_index 109
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 3, jumping to window_index 23
Skipping window window_78 due to NaN before position 9, jumping to window_index 87
Skipping window window_88 due to NaN before position 9, jumping to window_index 97
Skipping window window_98 due to NaN before position 9, jumping to window_index 107
Skipping window window_108 due to NaN before position 9, jumping to window_index 117
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 3, jumping to window_index 23
Skipping window window_86 due to NaN before position 9, jumping to window_index 95
Skipping window window_96 due to NaN before position 9, jumping to window_index 105
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 3, jumping to window_index 23
Skipping window window_33 due to NaN before position 9, jumping to window_index 42
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 7, jumping to window_index 47
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 7, jumping to window_index 47
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_90 due to NaN before position 9, jumping to window_index 99
Skipping window window_100 due to NaN before position 9, jumping to window_index 109
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 7, jumping to window_index 47
Skipping window window_64 due to NaN before position 9, jumping to window_index 73
Skipping window window_77 due to NaN before position 9, jumping to window_index 86
Skipping window window_87 due to NaN before position 9, jumping to window_index 96
Skipping window window_97 due to NaN before position 9, jumping to window_index 106
Skipping window window_107 due to NaN before position 9, jumping to window_index 116
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 7, jumping to window_index 47
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 7, jumping to window_index 87
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 1, jumping to window_index 81
Skipping window window_86 due to NaN before position 9, jumping to window_index 95
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_92 due to NaN before position 9, jumping to window_index 101
Skipping window window_102 due to NaN before position 9, jumping to window_index 111
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_106 due to NaN before position 9, jumping to window_index 115
Skipping window window_0 due to NaN before position 9, jumping to window_index 9
Skipping window window_10 due to NaN before position 9, jumping to window_index 19
Skipping window window_20 due to NaN before position 9, jumping to window_index 29
Skipping window window_30 due to NaN before position 9, jumping to window_index 39
Skipping window window_40 due to NaN before position 9, jumping to window_index 49
Skipping window window_50 due to NaN before position 9, jumping to window_index 59
Skipping window window_60 due to NaN before position 9, jumping to window_index 69
Skipping window window_70 due to NaN before position 9, jumping to window_index 79
Skipping window window_80 due to NaN before position 9, jumping to window_index 89
Skipping window window_106 due to NaN before position 9, jumping to window_index 115

     quali0 race0 quali1 race1 quali2 race2 quali3 race3 quali4 race4
0       7.0   4.0    7.0   3.0    7.0   5.0    9.0   8.0    5.0   3.0
1       7.0   3.0    7.0   5.0    9.0   8.0    5.0   3.0    9.0   5.0
2       7.0   5.0    9.0   8.0    5.0   3.0    9.0   5.0    8.0   5.0
3       9.0   8.0    5.0   3.0    9.0   5.0    8.0   5.0    3.0   5.0
4       5.0   3.0    9.0   5.0    8.0   5.0    3.0   5.0    2.0   3.0
...     ...   ...    ...   ...    ...   ...    ...   ...    ...   ...
1915   16.0  18.0   10.0   9.0    7.0   6.0   13.0  15.0    7.0   8.0
1916   10.0   9.0    7.0   6.0   13.0  15.0    7.0   8.0   13.0  11.0
1917    7.0   6.0   13.0  15.0    7.0   8.0   13.0  11.0   14.0  17.0
1918   13.0  15.0    7.0   8.0   13.0  11.0   14.0  17.0   16.0  18.0
1919    7.0   8.0   13.0  11.0   14.0  17.0   16.0  18.0   16.0  10.0

[1920 rows x 10 columns]

## Save windows

In [16]:
df_windows_raceonly.to_csv(config.FASTF1_DATA_DIR / "interim" / "df_windows_raceonly.csv", index=False)
df_windows_qualirace.to_csv(config.FASTF1_DATA_DIR / "interim" / "df_windows_qualirace.csv", index=False)

## Load windows

In [7]:
df_windows_raceonly = pd.read_csv(config.FASTF1_DATA_DIR / "interim" / "df_windows_raceonly.csv")
df_windows_qualirace = pd.read_csv(config.FASTF1_DATA_DIR / "interim" / "df_windows_qualirace.csv")

# Train Models

## Prepare Data for model training

In [8]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

def data_label_split(df_windows: pd.DataFrame):
	X = df_windows.iloc[:, :-1]
	y = df_windows.iloc[:, -1]
	return X, y

def normalize_features(X: pd.DataFrame):
   scaler = StandardScaler()
   X_normalized = scaler.fit_transform(X)
   return X_normalized

## XGBoost Models

### XGBoost Regressor

#### Race only

In [9]:
X, y = data_label_split(df_windows_raceonly)
X_normalized = normalize_features(X)

In [5]:
y.value_counts().sort_index()

race4
1.0     105
2.0     106
3.0     105
4.0     105
5.0     102
6.0     104
7.0     100
8.0      98
9.0      99
10.0    100
11.0     94
12.0     98
13.0     94
14.0     95
15.0     96
16.0     97
17.0     96
18.0    103
19.0    102
20.0     96
Name: count, dtype: int64

In [10]:
y = y - 1

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
	 X_normalized, y, test_size=0.2, stratify=y
)

In [12]:
model = xgb.XGBRegressor(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,

)

In [13]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [14]:
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

MAE: 4.136398564716031
R² Score: 0.1261324174042372

In [15]:
def train():
	X_train, X_test, y_train, y_test = train_test_split(
	 X_normalized, y, test_size=0.2, stratify=y
	)
	model = xgb.XGBRegressor(
	 n_estimators=100,
	 learning_rate=0.02,
	 max_depth=12,
	 subsample=0.8,
	 colsample_bytree=0.8,

	)
	model.fit(X_train, y_train)
	y_pred = model.predict(X_test)
	print("MAE:", mean_absolute_error(y_test, y_pred))
	print("R² Score:", r2_score(y_test, y_pred))
train()

MAE: 4.036842630620589
R² Score: 0.2537812789476679

## Save Model

In [19]:
model.save_model(config.FASTF1_MODELS_DIR / "xgb_raceonly_model.json")
model.save_model(config.FASTF1_MODELS_DIR / "xgb_raceonly_model.ubj")
print("Model saved successfully.")

Model saved successfully.

In [15]:
from sklearn.model_selection import GridSearchCV
xgb_model = xgb.XGBClassifier(objective='binary:logistic', eval_metric='logloss', use_label_encoder=False)
# Note: This is a small grid for demonstration. A real search would have more values.
param_grid = {
    'max_depth': range(3, 24),
    'n_estimators': range(50, 200, 30),
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}
# scoring='accuracy' is the metric to optimize
grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# 6. Print the best parameters found
print("Best hyperparameters found:")
print(grid_search.best_params_)

# 7. Get the best model and evaluate it on the test set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"\nAccuracy on test set with best model: {accuracy:.4f}")

Fitting 5 folds for each of 1680 candidates, totalling 8400 fits

/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   2.8s

/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   3.2s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=80, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1.0; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   3.4s

/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1.0; total time=   3.4s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=80, subsample=0.8; total time=   3.5s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1.0; total time=   3.5s[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1.0; total time=   3.5s

/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
Process LokyProcess-9:
Traceback (most recent call last):
  File "/home/dhiabenhamouda/.pyenv/versions/3.13.7/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/dhiabenhamouda/.pyenv/versions/3.13.7/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py", line 505, in _process_worker
    _process_reference_size = _get_memory_usage(pid, force_gc=True)
  File "/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py", line 110, in _get_memory_usage
    gc.collect()
    ~~~~~~~~~~^^
KeyboardInterrupt
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=1.0; total time=   0.6s

/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:28] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/media/dhiabenhamouda/Dhia/Work/F1WinnerPrediction/.venv/lib/python3.13/site-packages/xgboost/training.py:199: UserWarning: [16:00:28] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=110, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=3, n_estimators=140, subsample=0.8; total time=   0.5s

KeyboardInterrupt:

In [19]:
print(grid_search.best_params_)

{'colsample_bytree': 1.0, 'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 180, 'subsample': 1.0}

#### Quali Race

In [21]:
X, y = data_label_split(df_windows_qualirace)
X_normalized = normalize_features(X)

In [22]:
y = y -1

In [23]:
y.value_counts().sort_index()

race4
0.0     105
1.0     106
2.0     103
3.0     105
4.0      99
5.0     101
6.0      97
7.0      97
8.0      97
9.0      95
10.0     91
11.0     92
12.0     90
13.0     89
14.0     89
15.0     93
16.0     91
17.0     98
18.0     93
19.0     89
Name: count, dtype: int64

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
	 X_normalized, y, test_size=0.2, stratify=y
)

In [25]:
params = {'colsample_bytree': 1.0, 'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 180, 'subsample': 1.0}
# model = xgb.XGBRegressor(
#     n_estimators=100,
#     learning_rate=0.05,
#     max_depth=8,
#     subsample=0.8,
#     colsample_bytree=0.8,

# )
model = xgb.XGBRegressor(**params)

In [26]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=180,
             n_jobs=None, num_parallel_tree=None, ...)

In [28]:
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

MAE: 3.32574949786067
R² Score: 0.44451576906453427

In [29]:
model.save_model(config.FASTF1_MODELS_DIR / "xgb_model_qualirace.json")
model.save_model(config.FASTF1_MODELS_DIR / "xgb_model_qualirace.ubj")
print("Model saved successfully.")

Model saved successfully.