In [1]:
import numpy as np
import pandas as pd
from f1winnerprediction import (
	config, 
	io_fastf1,
	mapper
)
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report,roc_auc_score, roc_curve, auc, mean_absolute_error, r2_score, accuracy_score, f1_score
import fastf1
import fastf1.core
import xgboost as xgb
from pprint import pprint

pd.set_option('display.max_columns', None)

fastf1.Cache.enable_cache(config.FASTF1_RAW_CACHE_DIR.as_posix())

# Load sessions from DB

In [2]:
# sessions: dict[int, list[fastf1.core.Session]] = io_fastf1.fetch_race_sessions_cache(use_sessions_cache=False, use_checkpoint=False)
# sessions

# Load sessions from dump files

In [3]:
sessions: dict[int, list[fastf1.core.Session]] = io_fastf1.load_sessions_from_years()
sessions

{2021: [2021 Season Round 1: Bahrain Grand Prix - Race,
  2021 Season Round 2: Emilia Romagna Grand Prix - Race,
  2021 Season Round 3: Portuguese Grand Prix - Race,
  2021 Season Round 4: Spanish Grand Prix - Race,
  2021 Season Round 5: Monaco Grand Prix - Race,
  2021 Season Round 6: Azerbaijan Grand Prix - Race,
  2021 Season Round 7: French Grand Prix - Race,
  2021 Season Round 8: Styrian Grand Prix - Race,
  2021 Season Round 9: Austrian Grand Prix - Race,
  2021 Season Round 10: British Grand Prix - Race,
  2021 Season Round 11: Hungarian Grand Prix - Race,
  2021 Season Round 12: Belgian Grand Prix - Race,
  2021 Season Round 13: Dutch Grand Prix - Race,
  2021 Season Round 14: Italian Grand Prix - Race,
  2021 Season Round 15: Russian Grand Prix - Race,
  2021 Season Round 16: Turkish Grand Prix - Race,
  2021 Season Round 17: United States Grand Prix - Race,
  2021 Season Round 18: Mexico City Grand Prix - Race,
  2021 Season Round 19: São Paulo Grand Prix - Race,
  2021 Season Round 20: Qatar Grand Prix - Race,
  2021 Season Round 21: Saudi Arabian Grand Prix - Race,
  2021 Season Round 22: Abu Dhabi Grand Prix - Race],
 2022: [2022 Season Round 1: Bahrain Grand Prix - Race,
  2022 Season Round 2: Saudi Arabian Grand Prix - Race,
  2022 Season Round 3: Australian Grand Prix - Race,
  2022 Season Round 4: Emilia Romagna Grand Prix - Race,
  2022 Season Round 5: Miami Grand Prix - Race,
  2022 Season Round 6: Spanish Grand Prix - Race,
  2022 Season Round 7: Monaco Grand Prix - Race,
  2022 Season Round 8: Azerbaijan Grand Prix - Race,
  2022 Season Round 9: Canadian Grand Prix - Race,
  2022 Season Round 10: British Grand Prix - Race,
  2022 Season Round 11: Austrian Grand Prix - Race,
  2022 Season Round 12: French Grand Prix - Race,
  2022 Season Round 13: Hungarian Grand Prix - Race,
  2022 Season Round 14: Belgian Grand Prix - Race,
  2022 Season Round 15: Dutch Grand Prix - Race,
  2022 Season Round 16: Italian Grand Prix - Race,
  2022 Season Round 17: Singapore Grand Prix - Race,
  2022 Season Round 18: Japanese Grand Prix - Race,
  2022 Season Round 19: United States Grand Prix - Race,
  2022 Season Round 20: Mexico City Grand Prix - Race,
  2022 Season Round 21: São Paulo Grand Prix - Race,
  2022 Season Round 22: Abu Dhabi Grand Prix - Race],
 2023: [2023 Season Round 1: Bahrain Grand Prix - Race,
  2023 Season Round 2: Saudi Arabian Grand Prix - Race,
  2023 Season Round 3: Australian Grand Prix - Race,
  2023 Season Round 4: Azerbaijan Grand Prix - Race,
  2023 Season Round 5: Miami Grand Prix - Race,
  2023 Season Round 6: Monaco Grand Prix - Race,
  2023 Season Round 7: Spanish Grand Prix - Race,
  2023 Season Round 8: Canadian Grand Prix - Race,
  2023 Season Round 9: Austrian Grand Prix - Race,
  2023 Season Round 10: British Grand Prix - Race,
  2023 Season Round 11: Hungarian Grand Prix - Race,
  2023 Season Round 12: Belgian Grand Prix - Race,
  2023 Season Round 13: Dutch Grand Prix - Race,
  2023 Season Round 14: Italian Grand Prix - Race,
  2023 Season Round 15: Singapore Grand Prix - Race,
  2023 Season Round 16: Japanese Grand Prix - Race,
  2023 Season Round 17: Qatar Grand Prix - Race,
  2023 Season Round 18: United States Grand Prix - Race,
  2023 Season Round 19: Mexico City Grand Prix - Race,
  2023 Season Round 20: São Paulo Grand Prix - Race,
  2023 Season Round 21: Las Vegas Grand Prix - Race,
  2023 Season Round 22: Abu Dhabi Grand Prix - Race],
 2024: [2024 Season Round 1: Bahrain Grand Prix - Race,
  2024 Season Round 2: Saudi Arabian Grand Prix - Race,
  2024 Season Round 3: Australian Grand Prix - Race,
  2024 Season Round 4: Japanese Grand Prix - Race,
  2024 Season Round 5: Chinese Grand Prix - Race,
  2024 Season Round 6: Miami Grand Prix - Race,
  2024 Season Round 7: Emilia Romagna Grand Prix - Race,
  2024 Season Round 8: Monaco Grand Prix - Race,
  2024 Season Round 9: Canadian Grand Prix - Race,
  2024 Season Round 10: Spanish Grand Prix - Race,
  2024 Season Round 11: Austrian Grand Prix - Race,
  2024 Season Round 12: British Grand Prix - Race,
  2024 Season Round 13: Hungarian Grand Prix - Race,
  2024 Season Round 14: Belgian Grand Prix - Race,
  2024 Season Round 15: Dutch Grand Prix - Race,
  2024 Season Round 16: Italian Grand Prix - Race,
  2024 Season Round 17: Azerbaijan Grand Prix - Race,
  2024 Season Round 18: Singapore Grand Prix - Race,
  2024 Season Round 19: United States Grand Prix - Race,
  2024 Season Round 20: Mexico City Grand Prix - Race,
  2024 Season Round 21: São Paulo Grand Prix - Race,
  2024 Season Round 22: Las Vegas Grand Prix - Race,
  2024 Season Round 23: Qatar Grand Prix - Race,
  2024 Season Round 24: Abu Dhabi Grand Prix - Race],
 2025: [2025 Season Round 1: Australian Grand Prix - Race,
  2025 Season Round 2: Chinese Grand Prix - Race,
  2025 Season Round 3: Japanese Grand Prix - Race,
  2025 Season Round 4: Bahrain Grand Prix - Race,
  2025 Season Round 5: Saudi Arabian Grand Prix - Race,
  2025 Season Round 6: Miami Grand Prix - Race,
  2025 Season Round 7: Emilia Romagna Grand Prix - Race,
  2025 Season Round 8: Monaco Grand Prix - Race,
  2025 Season Round 9: Spanish Grand Prix - Race,
  2025 Season Round 10: Canadian Grand Prix - Race,
  2025 Season Round 11: Austrian Grand Prix - Race,
  2025 Season Round 12: British Grand Prix - Race,
  2025 Season Round 13: Belgian Grand Prix - Race,
  2025 Season Round 14: Hungarian Grand Prix - Race,
  2025 Season Round 15: Dutch Grand Prix - Race,
  2025 Season Round 16: Italian Grand Prix - Race,
  2025 Season Round 17: Azerbaijan Grand Prix - Race,
  2025 Season Round 18: Singapore Grand Prix - Race,
  2025 Season Round 19: United States Grand Prix - Race,
  2025 Season Round 20: Mexico City Grand Prix - Race,
  2025 Season Round 21: São Paulo Grand Prix - Race,
  2025 Season Round 22: Las Vegas Grand Prix - Race,
  2025 Season Round 23: Qatar Grand Prix - Race,
  2025 Season Round 24: Abu Dhabi Grand Prix - Race]}

In [4]:
driver_mapping = io_fastf1.build_drivers_dict(sessions)
driver_mapping

{'VET': {'index': 21},
 'GAS': {'index': 19},
 'BOT': {'index': 23},
 'RUS': {'index': 19},
 'STR': {'index': 19},
 'GIO': {'index': 21},
 'ALO': {'index': 19},
 'RIC': {'index': 17},
 'NOR': {'index': 19},
 'VER': {'index': 19},
 'MSC': {'index': 21},
 'HAM': {'index': 19},
 'MAZ': {'index': 21},
 'LAT': {'index': 21},
 'LEC': {'index': 19},
 'PER': {'index': 23},
 'RAI': {'index': 21},
 'SAI': {'index': 19},
 'TSU': {'index': 19},
 'OCO': {'index': 19},
 'KUB': {'index': 13},
 'ZHO': {'index': 23},
 'HUL': {'index': 19},
 'ALB': {'index': 19},
 'MAG': {'index': 23},
 'DEV': {'index': 9},
 'SAR': {'index': 14},
 'PIA': {'index': 19},
 'LAW': {'index': 19},
 'BEA': {'index': 19},
 'COL': {'index': 19},
 'DOO': {'index': 5},
 'ANT': {'index': 19},
 'HAD': {'index': 19},
 'BOR': {'index': 19}}

In [5]:
import importlib

importlib.reload(mapper)

In [6]:
gp_index_map: dict[str, dict[int, int]] = {}
gp_index_map = mapper.map_gp_indices_between_years(sessions)
pprint(gp_index_map)

WARNING:requests_cache.policy.expiration:GP index mapping incomplete for years 2021 and 2022.       Some GPs may be missing.
WARNING:requests_cache.policy.expiration:GP index mapping incomplete for years 2022 and 2023.       Some GPs may be missing.

{'2021-2022': {0: 0,
               1: 3,
               3: 5,
               4: 6,
               5: 7,
               6: 11,
               8: 10,
               9: 9,
               10: 12,
               11: 13,
               12: 14,
               13: 15,
               16: 18,
               17: 19,
               18: 20,
               20: 1,
               21: 21},
 '2022-2023': {0: 0,
               1: 1,
               2: 2,
               4: 4,
               5: 6,
               6: 5,
               7: 3,
               8: 7,
               9: 9,
               10: 8,
               12: 10,
               13: 11,
               14: 12,
               15: 13,
               16: 14,
               17: 15,
               18: 17,
               19: 18,
               20: 19,
               21: 21},
 '2023-2024': {0: 0,
               1: 1,
               2: 2,
               3: 16,
               4: 5,
               5: 7,
               6: 9,
               7: 8,
               8: 10,
               9: 11,
               10: 12,
               11: 13,
               12: 14,
               13: 15,
               14: 17,
               15: 3,
               16: 22,
               17: 18,
               18: 19,
               19: 20,
               20: 21,
               21: 23},
 '2024-2025': {0: 3,
               1: 4,
               2: 0,
               3: 2,
               4: 1,
               5: 5,
               6: 6,
               7: 7,
               8: 9,
               9: 8,
               10: 10,
               11: 11,
               12: 13,
               13: 12,
               14: 14,
               15: 15,
               16: 16,
               17: 17,
               18: 18,
               19: 19,
               20: 20,
               21: 21,
               22: 22,
               23: 23}}

# Prepare laptime data

In [7]:
years = config.YEARS_TO_FETCH
# Parse year by year
dataset = pd.DataFrame()
for year_first in tqdm(years):
	if (year_first+1) not in years:
		continue
	second_year = year_first + 1
 
	# Parse session by session
	for session_index, first_session in enumerate(sessions[year_first]):
    
		# Check if the GP index mapping exists
		gp_index_map_key = str(year_first) + "-" + str(second_year)
  
		if gp_index_map_key not in gp_index_map:
			print(f"GP: {gp_index_map_key} not found in mapping.")
			continue

		# Check if the session_index exists in the mapping
		# = if the GP was held in both years
		if session_index not in gp_index_map[gp_index_map_key]:
			print(f"Year: {year_first}, GP: {gp_index_map_key} has no mapped index.")
			continue
		
		try:
     
			# Get the mapped index
			mapped_index = gp_index_map[gp_index_map_key][session_index]
			print(f"Year: {year_first}, GP: {gp_index_map_key}, Mapped Index: {mapped_index}")
			second_session = sessions[second_year][mapped_index]
				
			# Now we have the current session and the corresponding session for next year
			mean_lap_time_first_year = first_session.laps["LapTime"].dt.total_seconds().groupby(first_session.laps["Driver"]).mean().sort_values()
			df_mean_lap_time_first_year = mean_lap_time_first_year.reset_index()
	
			mean_lap_time_latter_year = second_session.laps["LapTime"].dt.total_seconds().groupby(second_session.laps["Driver"]).mean().sort_values()
			df_mean_lap_time_next_year = mean_lap_time_latter_year.reset_index()	

			# Merge both DataFrames on 'Driver'
			merged_df = pd.merge(df_mean_lap_time_first_year, df_mean_lap_time_next_year, on="Driver", suffixes=('_first_year', '_latter_year'))
			print(merged_df)
		except Exception as e:
			print(f"An error occurred for Year: {year_first}, GP: {gp_index_map_key}, Mapped Index: {mapped_index}. Error: {e}")
			continue
		
		dataset = pd.concat([dataset, merged_df], ignore_index=True)
  
dataset.sort_values(by=['Driver'], inplace=True)
dataset

  0%|          | 0/5 [00:00<?, ?it/s]

Year: 2021, GP: 2021-2022, Mapped Index: 0
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           97.575291           102.753434
1     HAM           97.586200           102.864193
2     BOT           98.310564           102.977246
3     NOR           98.514473           103.682789
4     LEC           98.687255           100.697709
5     RIC           98.888291           103.658930
6     PER           99.570429           102.955804
7     SAI           99.839232           102.792667
8     TSU          100.171232           103.052105
9     GAS          100.181490           100.781023
10    STR          100.189464           103.499246
11    OCO          100.727182           103.035211
12    RUS          100.760982           102.040107
13    MSC          101.830982           103.265930
14    ALO          102.290452           103.087263
15    LAT          102.558608           103.778579
Year: 2021, GP: 2021-2022, Mapped Index: 3
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           89.361186            89.407500
1     VER           90.029968            87.745810
2     LEC           90.710952            88.635841
3     NOR           91.265694            88.298730
4     SAI           91.446516                  NaN
5     RIC           92.006919            89.187016
6     PER           92.041984            88.008143
7     OCO           92.042600            89.360339
8     STR           92.338525            89.310935
9     TSU           92.781656            88.715810
10    ALO           92.930131           124.153167
11    GAS           93.361672            88.389016
12    MSC           94.376898            88.876541
13    VET           94.400610            88.871079
14    BOT          101.964833            88.431222
15    RUS          101.981567            88.420508
16    LAT                 NaN            88.578164
Year: 2021, GP: 2021-2022 has no mapped index.
Year: 2021, GP: 2021-2022, Mapped Index: 5
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           84.661818            89.318318
1     VER           84.901833            88.492045
2     BOT           85.065000            89.400773
3     LEC           85.489333            89.691037
4     PER           85.626530            88.690106
5     RIC           85.779515            90.463877
6     SAI           85.793182            89.177015
7     NOR           86.342538            89.753182
8     OCO           86.557554            89.634424
9     GAS           86.560477            90.483415
10    STR           86.641031            90.812400
11    VET           86.723785            90.263046
12    RUS           86.868492            88.990939
13    LAT           87.044185            91.327047
14    ALO           87.049138            89.958800
15    MSC           87.365500            90.521815
16    TSU           88.196500            90.017231
Year: 2021, GP: 2021-2022, Mapped Index: 6
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           76.113077            89.520371
1     SAI           76.228051            89.517532
2     NOR           76.362141            90.589508
3     PER           76.375769            89.494774
4     VET           76.787321            91.683048
5     BOT           76.793000            91.489730
6     GAS           76.804051            90.651952
7     HAM           76.987833            91.155746
8     STR           77.168792            91.491333
9     OCO           77.648130            91.180444
10    RIC           77.699013            91.762714
11    ALO           77.705351            91.134143
12    RUS           78.034039            90.658206
13    LAT           78.048117            92.030323
14    TSU           78.057974            92.490629
15    MSC           79.684253           103.646083
16    LEC                 NaN            89.541419
Year: 2021, GP: 2021-2022, Mapped Index: 7
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          107.443171           109.641820
1     STR          108.112483           113.464867
2     PER          108.295477           110.042220
3     HAM          108.564045           111.071120
4     GAS          108.983136           111.430780
5     VET          109.016614           111.569980
6     LEC          109.101909           112.386450
7     TSU          109.307023           112.315306
8     NOR          109.607205           112.519549
9     BOT          109.623500           111.455396
10    SAI          110.067273           109.805750
11    RIC          110.863422           111.509080
12    RUS          111.728591           110.547000
13    ALO          112.039674           111.644020
14    LAT          112.040522           114.208694
15    MSC          112.256444           113.076918
16    OCO          120.568333           111.966480
Year: 2021, GP: 2021-2022, Mapped Index: 11
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           98.976792            99.867353
1     HAM           99.031585           100.920769
2     PER           99.143038           101.126500
3     BOT           99.252604           103.373170
4     NOR          100.184943           102.908264
5     RIC          100.408057           103.065736
6     GAS          100.422000           103.161509
7     ALO          100.442736           101.755096
8     VET          100.479925           102.033115
9     STR          100.711623           103.106811
10    SAI          100.851075           102.471396
11    RUS          101.034981           101.079173
12    TSU          101.118096           104.395706
13    OCO          101.132442           103.001340
14    LEC          101.281615            99.114235
15    LAT          101.331173           103.610051
16    MSC          101.921288           103.443509
Year: 2021, GP: 2021-2022 has no mapped index.
Year: 2021, GP: 2021-2022, Mapped Index: 10
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           70.909056            71.349915
1     BOT           71.162197            72.632671
2     NOR           71.191014            72.464557
3     HAM           71.563310            71.908859
4     PER           71.583915            75.696500
5     SAI           71.713901            71.160464
6     RIC           71.759690            72.580800
7     LEC           71.770958            71.328338
8     GAS           71.780099            72.824543
9     ALO           72.079814            72.610529
10    RUS           72.160271            72.158930
11    VET           72.204159            72.873486
12    TSU           72.242314            72.920743
13    STR           72.337429            72.768414
14    LAT           72.540629            73.472958
15    MSC           73.050826            72.423029
16    OCO                 NaN            72.292225
Year: 2021, GP: 2021-2022, Mapped Index: 9
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           93.035122            95.492125
1     LEC           93.079449            95.701354
2     BOT           93.235918           101.372316
3     NOR           93.656918            97.425673
4     RIC           93.922531            98.921480
5     SAI           94.967220            94.322809
6     TSU           95.444320           101.231608
7     STR           95.452640            99.869745
8     OCO           95.529480           101.551083
9     ALO           95.567020            98.378100
10    GAS           95.586840           100.909480
11    VET           95.627595            98.756740
12    PER           95.683694            97.309531
13    RUS           95.738653                  NaN
14    LAT           95.765469           100.089725
15    MSC           97.096673            98.782280
16    VER                 NaN            97.747020
Year: 2021, GP: 2021-2022, Mapped Index: 12
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           83.971206            85.482086
1     OCO           84.157294            86.768116
2     VET           84.201412            86.770188
3     ALO           84.370279            86.726464
4     SAI           84.407118            85.578443
5     GAS           85.142029            87.068145
6     VER           85.297206            85.370171
7     TSU           85.318647            88.657956
8     RUS           85.319897            85.546414
9     LAT           85.355368            87.752304
10    RIC           85.990716            87.135493
11    MSC           86.022134            87.150928
12    NOR          142.425000            86.488743
13    BOT                 NaN            86.480708
14    LEC                 NaN            85.599414
15    PER                 NaN            85.594286
16    STR                 NaN            86.880493
Year: 2021, GP: 2021-2022, Mapped Index: 13
   Driver  LapTime_first_year  LapTime_latter_year
0     VER             207.071           114.104500
1     RUS             209.066           114.594833
2     HAM             209.672                  NaN
3     RIC             211.567           116.618333
4     VET             214.550           115.896857
5     GAS             217.248           115.729780
6     OCO             218.650           115.987476
7     LEC             219.679           115.698238
8     LAT             222.556           116.503675
9     SAI             223.237           114.390976
10    ALO             227.661           115.717500
11    BOT             229.485           125.651000
12    NOR             234.181           116.726881
13    TSU             235.400           116.853405
14    MSC             236.578           117.157390
15    STR             241.179           116.622548
16    PER             245.276           114.245571
Year: 2021, GP: 2021-2022, Mapped Index: 14
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           75.074931            79.551606
1     HAM           75.365653            80.774847
2     BOT           75.859097            80.008981
3     GAS           76.298352            80.969194
4     LEC           76.368662            80.745861
5     ALO           76.772732            80.854542
6     SAI           76.801352            80.815125
7     PER           76.809563            80.846403
8     OCO           76.823451            80.887361
9     NOR           76.869366            80.862208
10    RIC           77.046789            81.118569
11    STR           77.467386            80.906000
12    VET           77.499157            81.024722
13    LAT           78.110643            81.272871
14    RUS           78.192014            80.650611
15    TSU           78.264125            78.557810
16    MSC           79.249217            81.052333
Year: 2021, GP: 2021-2022, Mapped Index: 15

 20%|██        | 1/5 [00:00<00:01,  3.72it/s]

   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           87.689400            91.186623
1     LEC           87.710980            91.131264
2     RIC           87.777429            88.488533
3     VER           88.549920            91.085113
4     NOR           89.179500            91.202226
5     PER           90.147275            91.200038
6     BOT           90.383314            92.844769
7     SAI           90.487294            91.180604
8     STR           90.619451            89.491103
9     ALO           90.677686            88.784484
10    RUS           90.682824            89.938673
11    OCO           90.690157            91.242151
12    LAT           90.770059            92.890442
13    VET           92.046923            88.822500
14    MSC           92.557808            91.246415
15    GAS          106.783000            91.205792
16    TSU                 NaN            92.862904
Year: 2021, GP: 2021-2022 has no mapped index.
Year: 2021, GP: 2021-2022 has no mapped index.
Year: 2021, GP: 2021-2022, Mapped Index: 18
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          101.367000           102.957380
1     HAM          101.390804           103.157060
2     PER          102.120982           103.417720
3     LEC          102.299964           103.090340
4     RIC          102.739393           108.883796
5     BOT          102.797857           105.768938
6     SAI          102.858875           115.016000
7     NOR          102.874054           107.362340
8     TSU          103.819655           107.702830
9     VET          103.856709           104.428300
10    ALO          104.270898           106.302135
11    STR          104.287145           108.429158
12    RUS          104.395473           104.327520
13    LAT          104.972909           108.123811
14    MSC          105.225259           107.745453
15    OCO          106.166775           107.646019
16    GAS          109.074429           106.012667
Year: 2021, GP: 2021-2022, Mapped Index: 19
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           83.367408            83.334211
1     HAM           83.600577            83.548099
2     PER           83.617437            83.589099
3     GAS           84.266634            85.139043
4     LEC           84.508775            84.302859
5     SAI           84.593086            84.152845
6     VET           84.702057            85.374671
7     ALO           84.896786            84.921651
8     NOR           84.933029            85.081757
9     RIC           85.442500            84.846657
10    OCO           85.606557            85.020829
11    STR           85.899087            85.524029
12    BOT           86.261145            85.130114
13    RUS           86.346203            84.030423
14    LAT           86.556174            86.545681
15    MSC                 NaN            85.651614
16    TSU                 NaN            85.627000
Year: 2021, GP: 2021-2022, Mapped Index: 20
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           78.068324            83.317930
1     VER           78.216155            83.438028
2     BOT           78.259535            83.614028
3     PER           78.630859            83.494704
4     LEC           78.765746            83.415282
5     SAI           78.798183            83.353451
6     GAS           79.243471            83.674803
7     OCO           79.476700            83.559634
8     ALO           79.483714            83.431056
9     NOR           79.526529            82.711640
10    VET           79.544929            83.665169
11    RUS           80.013414            83.296394
12    TSU           80.109314            84.947786
13    LAT           80.166614            83.818056
14    RIC           81.377837                  NaN
15    MSC           81.382971            83.717507
16    STR           82.164489            83.628113
Year: 2021, GP: 2021-2022 has no mapped index.
Year: 2021, GP: 2021-2022, Mapped Index: 1
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           97.348116           100.373896
1     VER           97.683488            96.884702
2     PER           98.137100            97.555340
3     OCO           98.570279            99.029404
4     RIC           98.839977           100.432242
5     BOT           99.272250            98.269281
6     LEC           99.611455            96.818340
7     NOR           99.675727           100.100188
8     GAS           99.935977           100.232854
9     SAI          100.036909            97.149255
10    LAT          100.909909            98.876143
11    ALO          101.625628            98.455062
12    STR          102.078022           101.483851
13    RUS          106.907818            98.022234
Year: 2021, GP: 2021-2022, Mapped Index: 21
   Driver  LapTime_first_year  LapTime_latter_year
0     PER           91.864927            90.965638
1     RUS           92.183720            91.410379
2     LAT           92.309820            94.472509
3     VER           92.401930            90.791621
4     HAM           92.412596            91.945218
5     NOR           93.410614            91.761172
6     ALO           93.456719            93.094630
7     SAI           93.491690            91.220793
8     TSU           93.500638            92.332500
9     OCO           93.505737            91.778517
10    GAS           93.515103            92.744965
11    BOT           93.531172            92.905561
12    LEC           93.538860            90.942845
13    VET           93.585053            92.238138
14    RIC           94.114250            92.227276
15    STR           95.181175            92.118017
16    MSC           95.192053            93.069895
Year: 2022, GP: 2022-2023, Mapped Index: 0
   Driver  LapTime_first_year  LapTime_latter_year
0     LEC          100.697709            99.644051
1     GAS          100.781023           100.184018
2     RUS          102.040107            99.870333
3     ZHO          102.161071           101.364018
4     VER          102.753434            98.890105
5     SAI          102.792667            99.733123
6     HAM          102.864193            99.784439
7     MAG          102.953298           100.955232
8     PER          102.955804            99.100404
9     BOT          102.977246           100.164614
10    OCO          103.035211           102.916244
11    TSU          103.052105           100.484316
12    ALO          103.087263            99.567947
13    STR          103.499246            99.846281
14    ALB          103.640632           100.465088
15    NOR          103.682789           102.606764
16    HUL          103.814263           101.082982
Year: 2022, GP: 2022-2023, Mapped Index: 1
   Driver  LapTime_first_year  LapTime_latter_year
0     LEC           96.818340            97.243000
1     VER           96.884702            94.926646
2     SAI           97.149255            97.046388
3     PER           97.555340            94.245021
4     RUS           98.022234            95.160354
5     BOT           98.269281            99.027667
6     ALO           98.455062            94.835875
7     OCO           99.029404            97.465347
8     ZHO           99.546170            99.019080
9     HUL           99.768277            98.909640
10    NOR          100.100188            99.226780
11    MAG          100.147688            98.794400
12    GAS          100.232854            97.530796
13    HAM          100.373896            95.643625
14    STR          101.483851            97.324000
15    ALB          102.143717           100.944320
Year: 2022, GP: 2022-2023, Mapped Index: 2
   Driver  LapTime_first_year  LapTime_latter_year
0     LEC           88.379750                  NaN
1     PER           90.010123            86.380346
2     RUS           90.061772            93.610800
3     HAM           90.181070            87.488887
4     NOR           90.651544            86.561673
5     BOT           90.960368            87.864843
6     GAS           91.095351            86.081750
7     STR           91.220105            86.121269
8     MAG           91.368429            87.232920
9     TSU           91.473607            87.798346
10    VER           91.534000            85.469385
11    ALO           91.784000            85.773731
12    OCO           91.866052            86.749154
13    ALB           92.171207           102.973500
14    ZHO           92.211086            87.850135
15    SAI           99.028000            86.093808
Year: 2022, GP: 2022-2023 has no mapped index.
Year: 2022, GP: 2022-2023, Mapped Index: 4
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           94.916774            92.249842
1     NOR           96.139538            93.788737
2     LEC           96.148093            93.179456
3     TSU           96.492241            93.378070
4     SAI           97.434564            92.907930
5     PER           97.519291            92.344298
6     GAS           97.572667            93.226509
7     HAM           97.716218            93.148947
8     RUS           97.769873            92.832807
9     BOT           97.828582            93.506632
10    ALO           98.934732            92.711333
11    OCO           98.937518            93.269544
12    ALB           98.999768            93.528105
13    STR           99.080000            93.385877
14    MAG           99.197436            93.354140
15    ZHO          102.172167            93.625982
Year: 2022, GP: 2022-2023, Mapped Index: 6
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           88.492045            79.968788
1     PER           88.690106            80.511394
2     RUS           88.990939            80.459530
3     SAI           89.177015            80.661182
4     HAM           89.318318            80.333788
5     BOT           89.400773            81.967431
6     OCO           89.634424            81.017909
7     LEC           89.691037            81.096348
8     NOR           89.753182            81.666615
9     ALO           89.958800            80.940409
10    TSU           90.017231            81.035697
11    GAS           90.483415            81.082879
12    STR           90.812400            80.928182
13    MAG           91.455172            81.784923
14    ZHO           91.984679            81.057848
15    ALB           92.043797            81.625354
Year: 2022, GP: 2022-2023, Mapped Index: 5
   Driver  LapTime_first_year  LapTime_latter_year
0     PER           89.494774            86.592158
1     SAI           89.517532            84.556038
2     VER           89.520371            83.743333
3     LEC           89.541419            84.536795
4     NOR           90.589508            84.883649
5     GAS           90.651952            84.542846
6     RUS           90.658206            84.400821
7     ALO           91.134143            84.101295
8     HAM           91.155746            84.244128
9     OCO           91.180444            84.217564
10    BOT           91.489730            85.207052
11    STR           91.491333            80.782472
12    ZHO           92.128581            85.764052
13    TSU           92.490629            86.046382
14    ALB           95.880404            85.859610
15    MAG          105.018526            86.445449
Year: 2022, GP: 2022-2023, Mapped Index: 3
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          109.641820           105.890396
1     SAI          109.805750           106.845750
2     PER          110.042220           106.544898
3     RUS          110.547000           107.597042
4     HAM          111.071120           109.083680
5     GAS          111.430780           110.858196
6     BOT          111.455396           110.794306
7     ALO          111.644020           107.282449
8     OCO          111.966480           109.258041
9     ALB          112.230959           110.805078
10    TSU          112.315306           109.888020
11    LEC          112.386450           107.078571
12    NOR          112.519549           109.789300
13    MAG          112.623161           109.524220
14    STR          113.464867           107.055188
15    ZHO          114.382522           110.378235
Year: 2022, GP: 2022-2023, Mapped Index: 7
   Driver  LapTime_first_year  LapTime_latter_year
0     PER           81.366000            81.276800
1     TSU           81.896638            81.596729
2     VER           82.596529            80.547829
3     SAI           82.610714            80.855543
4     HAM           82.696614            80.750229
5     RUS           82.772429            80.179846
6     LEC           82.813214            80.814229
7     OCO           82.937814            81.429143
8     ALO           82.952886            80.684543
9     BOT           82.957200            81.468286
10    ZHO           82.981557            81.967029
11    STR           83.142557            81.467857
12    ALB           83.237857            81.416586
13    GAS           83.242000            81.479957
14    NOR           83.270029            81.453014
15    MAG           83.570529            82.733435
Year: 2022, GP: 2022-2023, Mapped Index: 9
   Driver  LapTime_first_year  LapTime_latter_year
0     SAI           94.322809            98.776654
1     HAM           95.492125            97.489686
2     LEC           95.701354            98.762058
3     PER           97.309531            98.650385
4     NOR           97.425673            97.163431
5     VER           97.747020            96.832686
6     ALO           98.378100            98.733288
7     MAG           98.852440            94.706613
8     STR           99.869745            98.835019
9     GAS          100.909480            99.991289
10    TSU          101.231608            99.003135
11    BOT          101.372316            98.899385
12    OCO          101.551083            95.150111
13    ALB                 NaN            98.746462
14    RUS                 NaN            98.618154
15    ZHO                 NaN            98.976115
Year: 2022, GP: 2022-2023, Mapped Index: 8
   Driver  LapTime_first_year  LapTime_latter_year
0     SAI           71.160464            72.605408
1     LEC           71.328338            72.376930
2     VER           71.349915            72.304324
3     HAM           71.908859            72.856380
4     RUS           72.158930            72.986056
5     OCO           72.292225            73.510671
6     NOR           72.464557            72.675127
7     MAG           72.513257            74.020000
8     ALO           72.610529            72.731324
9     BOT           72.632671            73.948343
10    ALB           72.698414            73.286958
11    STR           72.768414            73.135915
12    ZHO           72.793014            73.689143
13    GAS           72.824543            73.116535
14    TSU           72.920743            73.978286
15    PER           75.696500            72.546408
Year: 2022, GP: 2022-2023 has no mapped index.
Year: 2022, GP: 2022-2023, Mapped Index: 10
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           85.370171            84.123343
1     HAM           85.482086            84.682400
2     RUS           85.546414            85.063700
3     SAI           85.578443            85.138671
4     PER           85.594286            84.660529
5     LEC           85.599414            85.056443
6     BOT           86.480708            85.778449
7     NOR           86.488743            84.605214
8     ALO           86.726464            85.204900
9     OCO           86.768116           104.073000
10    STR           86.880493            85.554333
11    GAS           87.068145           124.981000
12    RIC           87.135493            85.867986
13    ZHO           87.146768            86.219203
14    MAG           87.564290            86.536014
15    ALB           87.576609            85.764072
16    TSU           88.657956            86.089522
Year: 2022, GP: 2022-2023, Mapped Index: 11
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          114.104500           112.510227
1     PER          114.245571           113.017159
2     SAI          114.390976           117.123696
3     RUS          114.594833           113.944341
4     LEC          115.698238           113.243386
5     ALO          115.717500           113.787136
6     GAS          115.729780           114.398500
7     OCO          115.987476           114.208386
8     ALB          116.506357           114.696227
9     RIC          116.618333           114.852750
10    STR          116.622548           114.313409
11    NOR          116.726881           114.185659
12    ZHO          116.796000           114.679341
13    TSU          116.853405           114.333432
14    MAG          116.969220           114.822818
15    BOT          125.651000           114.446386
16    HAM                 NaN           113.639114
Year: 2022, GP: 2022-2023, Mapped Index: 12
   Driver  LapTime_first_year  LapTime_latter_year
0     TSU           78.557810            85.575457
1     VER           79.551606            84.772817
2     BOT           80.008981            85.774757
3     RUS           80.650611            85.503157
4     LEC           80.745861            87.349878
5     HAM           80.774847            84.653271
6     SAI           80.815125            84.591543
7     PER           80.846403            84.497386
8     ALO           80.854542            85.246775
9     NOR           80.862208            84.886957
10    OCO           80.887361            85.207743
11    STR           80.906000            85.591014
12    GAS           80.969194            84.489300
13    ALB           81.016153            84.988514
14    MAG           81.106139            86.855718
15    ZHO           81.112403            84.215161
Year: 2022, GP: 2022-2023, Mapped Index: 13
   Driver  LapTime_first_year  LapTime_latter_year
0     ALO           88.784484            87.596804
1     STR           89.491103            88.354960
2     RUS           89.938673            87.042569
3     VER           91.085113            86.689078
4     LEC           91.131264            86.912157
5     SAI           91.180604            86.908549
6     HAM           91.186623            87.427882
7     PER           91.200038            86.807980
8     NOR           91.202226            87.580235
9     GAS           91.205792            88.296720
10    ZHO           91.234358            88.278120
11    OCO           91.242151            89.101974
12    BOT           92.844769            87.962500
13    TSU           92.862904                  NaN
14    MAG           92.926096            88.675340
Year: 2022, GP: 2022-2023, Mapped Index: 14
   Driver  LapTime_first_year  LapTime_latter_year
0     PER          117.185314           103.103459
1     SAI          118.132275           100.967300
2     LEC          118.342808           102.193918
3     NOR          119.797264           101.916705
4     HAM          119.844882           101.915754
5     VER          120.415538           102.406180
6     GAS          121.216231           102.723967
7     MAG          122.758685           102.347083
8     BOT          123.223759           104.464820
9     ALO          123.477556           103.405885
10    RUS          124.810769           101.961383
11    TSU          126.818733                  NaN
12    OCO          127.645333           102.653659
13    ALB          129.044783           102.392817
14    ZHO          129.933333           103.685689
Year: 2022, GP: 2022-2023, Mapped Index: 15
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          109.074292            99.060160
1     LEC          110.268083           100.036760
2     PER          110.338208           108.709200
3     OCO          111.059000           102.175961
4     HAM          111.226708           100.208780
5     ALO          111.571750           100.684940
6     RUS          111.736208           100.415620

 40%|████      | 2/5 [00:00<00:00,  4.55it/s]

   Driver  LapTime_first_year  LapTime_latter_year
0     VER           83.334211            83.602588
1     HAM           83.548099            84.115485
2     PER           83.589099           103.446000
3     RUS           84.030423            86.489371
4     SAI           84.152845            84.400544
5     LEC           84.302859            84.191603
6     RIC           84.846657            85.567493
7     ALO           84.921651            88.685935
8     OCO           85.020829            86.762800
9     NOR           85.081757            86.347529
10    BOT           85.130114            87.028157
11    GAS           85.139043            86.819014
12    ALB           85.166171            85.640768
13    ZHO           85.325157            87.062871
14    STR           85.524029            87.452123
15    TSU           85.627000            87.057014
16    MAG           85.673500            86.645581
Year: 2022, GP: 2022-2023, Mapped Index: 19
   Driver  LapTime_first_year  LapTime_latter_year
0     NOR           82.711640            78.438971
1     RUS           83.296394            80.730696
2     HAM           83.317930            79.155514
3     SAI           83.353451            78.938271
4     LEC           83.415282                  NaN
5     ALO           83.431056            78.743186
6     VER           83.438028            78.338914
7     PER           83.494704            78.740800
8     OCO           83.559634            79.070783
9     BOT           83.614028            81.439553
10    STR           83.628113            78.846500
11    GAS           83.674803            78.671286
12    ZHO           83.709423            85.580714
13    ALB           83.803662                  NaN
14    TSU           84.947786            78.840429
15    MAG                 NaN                  NaN
16    RIC                 NaN            78.257145
Year: 2022, GP: 2022-2023, Mapped Index: 21
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           90.791621            90.045241
1     LEC           90.942845            90.355466
2     PER           90.965638            90.328914
3     SAI           91.220793            91.419702
4     RUS           91.410379            90.395724
5     NOR           91.761172            90.463931
6     OCO           91.778517            91.189603
7     HAM           91.945218            90.811172
8     STR           92.118017            91.004414
9     RIC           92.227276            91.014707
10    TSU           92.332500            90.788138
11    ZHO           92.718667            91.587000
12    ALB           92.734105            91.307034
13    GAS           92.744965            91.258345
14    BOT           92.905561            91.842719
15    ALO           93.094630            90.726483
16    MAG           93.274421            91.885965
Year: 2023, GP: 2023-2024, Mapped Index: 0
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           98.890105            96.574421
1     PER           99.100404            96.968404
2     ALO           99.567947            97.888228
3     LEC           99.644051            97.270368
4     SAI           99.733123            97.014947
5     HAM           99.784439            97.457298
6     STR           99.846281            98.209789
7     RUS           99.870333            97.395263
8     BOT          100.164614            98.503745
9     GAS          100.184018            98.877839
10    ALB          100.465088            98.511214
11    TSU          100.484316            98.468286
12    SAR          100.676286            99.327352
13    MAG          100.955232            98.447464
14    HUL          101.082982            98.613821
15    ZHO          101.364018            98.419661
16    NOR          102.606764            97.424561
17    OCO          102.916244            98.860571
18    PIA          103.275769            97.558316
Year: 2023, GP: 2023-2024, Mapped Index: 1
   Driver  LapTime_first_year  LapTime_latter_year
0     PER           94.245021            93.867729
1     ALO           94.835875            94.557750
2     VER           94.926646            93.608229
3     RUS           95.160354            94.753188
4     HAM           95.643625            94.955042
5     LEC           97.243000            94.101208
6     STR           97.324000            97.121600
7     OCO           97.465347            97.310542
8     GAS           97.530796           121.453000
9     TSU           97.754837            97.275917
10    MAG           98.794400            96.918020
11    HUL           98.909640            95.764625
12    ZHO           99.019080            98.048479
13    BOT           99.027667            97.688667
14    PIA           99.198300            94.468937
15    SAR           99.223740            97.349375
16    NOR           99.226780            94.858021
17    ALB          100.944320            96.972327
Year: 2023, GP: 2023-2024, Mapped Index: 2
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           85.469385            84.890667
1     ALO           85.773731            84.617845
2     GAS           86.081750            85.312211
3     SAI           86.093808            83.221431
4     STR           86.121269            84.828707
5     PER           86.380346            84.192276
6     HUL           86.529365            85.024069
7     NOR           86.561673            83.323224
8     OCO           86.749154            85.628456
9     MAG           87.232920            84.753053
10    PIA           87.279308            83.838155
11    HAM           87.488887            85.228400
12    TSU           87.798346            84.869724
13    ZHO           87.850135            85.458526
14    BOT           87.864843            85.424018
15    RUS           93.610800            83.655964
16    ALB          102.973500            84.769333
17    LEC                 NaN            83.262224
Year: 2023, GP: 2023-2024, Mapped Index: 16
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          105.890396           109.063102
1     PER          106.544898           108.595878
2     SAI          106.845750           108.607510
3     STR          107.055188           111.135111
4     LEC          107.078571           108.677840
5     ALO          107.282449           110.223980
6     RUS          107.597042           109.127900
7     HAM          109.083680           110.332620
8     OCO          109.258041           110.882449
9     HUL          109.712646           110.392660
10    NOR          109.789300           109.239420
11    TSU          109.888020           115.903643
12    PIA          109.967680           108.493460
13    ZHO          110.378235           110.671041
14    BOT          110.794306           111.245939
15    ALB          110.805078           110.254460
16    GAS          110.858196           110.614320
Year: 2023, GP: 2023-2024, Mapped Index: 5
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           92.249842            94.686696
1     PER           92.344298            95.868877
2     ALO           92.711333            96.262860
3     RUS           92.832807            96.222193
4     SAI           92.907930            95.811982
5     HAM           93.148947            95.902825
6     LEC           93.179456            94.780893
7     GAS           93.226509            96.400596
8     OCO           93.269544            96.309158
9     MAG           93.354140            96.571211
10    TSU           93.378070            96.071246
11    STR           93.385877            96.404368
12    BOT           93.506632            96.530386
13    ALB           93.528105            96.946789
14    HUL           93.564754            96.327456
15    ZHO           93.625982            96.488684
16    NOR           93.788737            94.522071
17    PIA           94.263411            95.521268
18    SAR           94.511232            95.686667
Year: 2023, GP: 2023-2024, Mapped Index: 7
   Driver  LapTime_first_year  LapTime_latter_year
0     STR           80.782472           113.177908
1     VER           83.743333           109.765766
2     ALO           84.101295           113.150105
3     OCO           84.217564                  NaN
4     HAM           84.244128           109.839610
5     RUS           84.400821           109.697364
6     LEC           84.536795           109.320740
7     GAS           84.542846           112.412922
8     SAI           84.556038           109.486688
9     NOR           84.883649           109.565429
10    PIA           85.012195           109.436091
11    BOT           85.207052           113.158447
12    ZHO           85.764052           113.826500
13    ALB           85.859610           112.332545
14    TSU           86.046382           112.143390
15    MAG           86.445449                  NaN
16    HUL           86.585342                  NaN
17    PER           86.592158                  NaN
18    SAR           86.907408           113.218158
Year: 2023, GP: 2023-2024, Mapped Index: 9
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           79.968788            80.306470
1     HAM           80.333788            80.576015
2     RUS           80.459530            80.644652
3     PER           80.511394            81.208348
4     SAI           80.661182            80.776591
5     STR           80.928182            81.930446
6     ALO           80.940409            81.688062
7     OCO           81.017909            81.395697
8     TSU           81.035697            82.525092
9     ZHO           81.057848            81.780046
10    GAS           81.082879            81.246242
11    LEC           81.096348            80.650545
12    PIA           81.264846            80.817985
13    HUL           81.465185            81.430939
14    ALB           81.625354            82.436554
15    NOR           81.666615            80.340091
16    MAG           81.784923            82.384846
17    BOT           81.967431            82.362154
18    SAR           81.994108            82.892078
Year: 2023, GP: 2023-2024, Mapped Index: 8
   Driver  LapTime_first_year  LapTime_latter_year
0     RUS           80.179846            90.558275
1     VER           80.547829            90.477304
2     ALO           80.684543            90.668812
3     HAM           80.750229            90.473652
4     LEC           80.814229            95.612718
5     SAI           80.855543            91.584490
6     PER           81.276800            91.814160
7     ALB           81.416586            91.632412
8     OCO           81.429143            90.714696
9     NOR           81.453014            90.508464
10    STR           81.467857            90.702464
11    BOT           81.468286            90.820391
12    PIA           81.477843            90.574899
13    GAS           81.479957            90.685319
14    TSU           81.596729            91.100232
15    SAR           81.678667            93.037909
16    HUL           81.960739            90.762551
17    ZHO           81.967029            92.321941
18    MAG           82.733435            90.831203
Year: 2023, GP: 2023-2024, Mapped Index: 10
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           72.304324            71.690859
1     LEC           72.376930            72.251465
2     PER           72.546408            72.077042
3     SAI           72.605408            71.370859
4     NOR           72.675127            71.735219
5     ALO           72.731324            73.006543
6     HAM           72.856380            71.632958
7     RUS           72.986056            71.307014
8     GAS           73.116535            72.176958
9     STR           73.135915            72.471886
10    ALB           73.286958            72.480914
11    OCO           73.510671            72.269338
12    SAR           73.571300            73.465319
13    ZHO           73.689143            72.966857
14    BOT           73.948343            72.602471
15    TSU           73.978286            72.513471
16    PIA           74.002514            71.333859
17    MAG           74.020000            72.157085
18    HUL           82.047917            72.068817
Year: 2023, GP: 2023-2024, Mapped Index: 11
   Driver  LapTime_first_year  LapTime_latter_year
0     MAG           94.706613            96.869462
1     OCO           95.150111            99.154820
2     VER           96.832686            95.163923
3     NOR           97.163431            95.280885
4     HAM           97.489686            95.135750
5     PIA           98.552192            95.374769
6     RUS           98.618154            96.111424
7     PER           98.650385            99.301280
8     ALO           98.733288            96.358385
9     ALB           98.746462            96.450885
10    LEC           98.762058            97.794745
11    SAI           98.776654            96.045712
12    STR           98.835019            96.223615
13    SAR           98.857115            96.846519
14    BOT           98.899385            97.821176
15    HUL           98.915404            96.207327
16    ZHO           98.976115           100.030700
17    TSU           99.003135            96.660808
18    GAS           99.991289                  NaN
Year: 2023, GP: 2023-2024, Mapped Index: 12
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           84.123343            84.333400
1     NOR           84.605214            84.059000
2     PER           84.660529            84.596871
3     HAM           84.682400            84.240986
4     PIA           85.017229            84.028414
5     LEC           85.056443            84.309643
6     RUS           85.063700            84.633671
7     SAI           85.138671            84.358029
8     ALO           85.204900            85.206414
9     STR           85.554333            85.142357
10    ALB           85.764072            85.779101
11    BOT           85.778449            85.904319
12    RIC           85.867986            85.505986
13    HUL           86.085971            85.727145
14    TSU           86.089522            85.132114
15    ZHO           86.219203            86.167928
16    SAR           86.406328            86.008406
17    MAG           86.536014            85.902768
18    OCO          104.073000            86.129246
19    GAS          124.981000            86.644091
Year: 2023, GP: 2023-2024, Mapped Index: 13
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          112.510227           109.233318
1     PER          113.017159           110.005341
2     LEC          113.243386           109.217932
3     HAM          113.639114           109.035591
4     ALO          113.787136           110.159159
5     RUS          113.944341           109.023636
6     NOR          114.185659           109.247500
7     OCO          114.208386           110.218000
8     STR          114.313409           110.455705
9     TSU          114.333432           110.767659
10    GAS          114.398500           110.486477
11    BOT          114.446386           110.629045
12    ZHO          114.679341           119.807250
13    ALB          114.696227           110.470250
14    MAG          114.822818           110.537977
15    RIC          114.852750           110.271955
16    SAR          114.884682           110.979477
17    HUL          115.020455           111.042568
18    SAI          117.123696           109.473523
19    PIA                 NaN           109.050295
Year: 2023, GP: 2023-2024, Mapped Index: 14
   Driver  LapTime_first_year  LapTime_latter_year
0     ZHO           84.215161            78.307686
1     GAS           84.489300            76.818634
2     PER           84.497386            76.181403
3     SAI           84.591543            76.078556
4     HAM           84.653271            76.321083
5     VER           84.772817            75.950208
6     NOR           84.886957            75.632208
7     ALB           84.988514            77.270845
8     PIA           85.140800            76.011889
9     OCO           85.207743            77.357704
10    ALO           85.246775            76.888056
11    RUS           85.503157            76.251889
12    TSU           85.575457            77.615000
13    STR           85.591014            76.989169
14    HUL           85.618386            76.968070
15    BOT           85.774757            77.839529
16    MAG           86.855718            77.622901
17    LEC           87.349878            75.985528
18    SAR           93.030571            77.606451
Year: 2023, GP: 2023-2024, Mapped Index: 15
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           86.689078            85.257717
1     PER           86.807980            85.563679
2     SAI           86.908549            84.836755
3     LEC           86.912157            84.542019
4     RUS           87.042569            85.291358
5     HAM           87.427882            84.972585
6     ALB           87.573510            85.814774
7     NOR           87.580235            84.658113
8     ALO           87.596804            85.834377
9     BOT           87.962500            86.691115
10    PIA           88.061160            84.592283
11    ZHO           88.278120            86.938115
12    GAS           88.296720            86.520596
13    STR           88.354960            87.004519
14    HUL           88.464720            86.761481
15    MAG           88.675340            85.642057
16    OCO           89.101974            86.411269
17    TSU                 NaN            90.952714
Year: 2023, GP: 2023-2024, Mapped Index: 17
   Driver  LapTime_first_year  LapTime_latter_year
0     SAI          100.967300            99.171129
1     HAM          101.915754            98.997081
2     NOR          101.916705            97.622113
3     RUS          101.961383            98.606629
4     LEC          102.193918            98.629048
5     MAG          102.347083           100.736536
6     ALB          102.392817           104.046867
7     VER          102.406180            97.959935
8     OCO          102.653659            99.943869
9     GAS          102.723967           100.190656
10    PIA          102.805459            98.296677
11    PER          103.103459            99.298279
12    HUL          103.405557            99.273951
13    ALO          103.405885            99.236787
14    ZHO          103.685689           100.160508
15    BOT          104.464820           100.170492
16    TSU                 NaN            99.366607
Year: 2023, GP: 2023-2024, Mapped Index: 3
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           99.060160            97.637510
1     NOR           99.495700            98.261392
2     PIA           99.857900            98.760941
3     LEC          100.036760            98.537588
4     SAI          100.174460            98.135137
5     HAM          100.208780            98.922863
6     RUS          100.415620            98.978902
7     ALO          100.684940            98.639314
8     GAS          101.037680           102.096196
9     TSU          101.432571           100.239700
10    HUL          101.597306           100.182440
11    ZHO          101.666184           115.406273
12    MAG          102.016163           101.488706
13    OCO          102.175961           101.825667
14    STR          104.807529           101.298843
15    ALB          105.336783                  NaN
16    SAR          108.365211           102.584353
17    PER          108.709200            97.903706
18    BOT          136.214000           101.448647
Year: 2023, GP: 2023-2024, Mapped Index: 22
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           91.178732            91.006566
1     PIA           91.260625            94.760750
2     LEC           91.910161            93.575745
3     ALO           92.064411            96.231404
4     OCO           92.340161                  NaN

 60%|██████    | 3/5 [00:00<00:00,  4.68it/s]

   Driver  LapTime_first_year  LapTime_latter_year
0     LEC           99.869689            98.805040
1     VER           99.957867            98.851020
2     RUS          100.396489            98.519380
3     OCO          100.759933           100.572020
4     GAS          100.989356           102.464867
5     PIA          101.140956            99.546680
6     ALB          101.280778           101.280840
7     PER          101.395630            99.781660
8     STR          101.584500           100.201420
9     MAG          101.701778            99.915440
10    ZHO          101.774356           100.001080
11    SAI          101.916957            98.757500
12    HAM          102.537370            98.665640
13    ALO          102.586609            99.903280
14    HUL          103.429488            99.715540
15    TSU          105.027977            99.775540
16    BOT          107.447020           100.760286
17    NOR          124.844500            99.387080
Year: 2023, GP: 2023-2024, Mapped Index: 23
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           90.045241            90.398931
1     PER           90.328914                  NaN
2     LEC           90.355466            90.089983
3     RUS           90.395724            90.186707
4     NOR           90.463931            89.539500
5     PIA           90.588121            90.984690
6     ALO           90.726483            90.959724
7     TSU           90.788138            91.368930
8     HAM           90.811172            90.168517
9     STR           91.004414            91.346737
10    GAS           91.258345            90.790534
11    ALB           91.307034            91.307754
12    SAI           91.419702            89.640052
13    HUL           91.488276            90.842155
14    ZHO           91.587000            91.413947
15    BOT           91.842719            94.909333
16    MAG           91.885965            92.471719
Year: 2024, GP: 2024-2025, Mapped Index: 3
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           96.574421           101.295263
1     SAI           97.014947           102.382955
2     LEC           97.270368           100.018643
3     RUS           97.395263            99.948750
4     NOR           97.424561            99.984000
5     HAM           97.457298           100.272036
6     PIA           97.558316            99.524375
7     ALO           97.888228           100.858357
8     STR           98.209789           100.934000
9     TSU           98.468286           100.589036
10    ALB           98.511214           100.663357
11    HUL           98.613821           101.629947
12    OCO           98.860571           101.468053
13    GAS           98.877839           101.323456
Year: 2024, GP: 2024-2025, Mapped Index: 4
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           93.608229            94.357229
1     LEC           94.101208            94.547104
2     PIA           94.468937            94.322646
3     ALO           94.557750            96.135208
4     RUS           94.753188            94.932833
5     NOR           94.858021            94.714229
6     HAM           94.955042            95.272271
7     HUL           95.764625            96.809021
8     BEA           96.048245            96.305375
9     ALB           96.972327            95.926667
10    STR           97.121600            96.807149
11    TSU           97.275917           165.662000
12    OCO           97.310542            96.801417
13    GAS          121.453000                  NaN
Year: 2024, GP: 2024-2025, Mapped Index: 0
   Driver  LapTime_first_year  LapTime_latter_year
0     SAI           83.221431                  NaN
1     LEC           83.262224           103.933528
2     NOR           83.323224           103.428302
3     RUS           83.655964           103.686340
4     PIA           83.838155           102.084462
5     ALO           84.617845            98.517379
6     ALB           84.769333           104.672389
7     STR           84.828707           104.730130
8     TSU           84.869724           104.085698
9     VER           84.890667           103.341151
10    HUL           85.024069           104.740167
11    HAM           85.228400           103.967189
12    GAS           85.312211           104.889167
13    OCO           85.628456           103.848698
Year: 2024, GP: 2024-2025, Mapped Index: 2
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           97.637510            92.961943
1     SAI           98.135137            94.360604
2     NOR           98.261392            92.988792
3     LEC           98.537588            93.265660
4     ALO           98.639314            94.043698
5     PIA           98.760941            93.002113
6     HAM           98.922863            93.512547
7     RUS           98.978902            93.289528
8     HUL          100.182440            94.508302
9     TSU          100.239700            94.063849
10    STR          101.298843            94.998308
11    OCO          101.825667            94.536245
12    GAS          102.096196            94.134057
13    ALB                 NaN            93.723585
Year: 2024, GP: 2024-2025, Mapped Index: 1
   Driver  LapTime_first_year  LapTime_latter_year
0     VER          105.235453            97.708607
1     STR          105.803321            98.664821
2     LEC          106.020943            97.825661
3     SAI          107.085852            98.775232
4     ALO          107.299648           111.393500
5     NOR          107.444545            97.585250
6     RUS          107.987909            97.609339
7     PIA          108.321364            97.411179
8     HUL          108.411909            99.550036
9     HAM          109.116786            97.864411
10    OCO          109.202964            98.303482
11    ALB          109.251071            98.416911
12    GAS          109.317446            98.611089
13    TSU          111.046731            99.609764
Year: 2024, GP: 2024-2025, Mapped Index: 5
   Driver  LapTime_first_year  LapTime_latter_year
0     NOR           94.522071            93.617842
1     VER           94.686696            94.237596
2     LEC           94.780893            94.537246
3     PIA           95.521268            93.536614
4     SAI           95.811982            94.599368
5     HAM           95.902825            94.592509
6     TSU           96.071246            94.754754
7     RUS           96.222193            94.197035
8     ALO           96.262860            95.581536
9     OCO           96.309158            94.975316
10    HUL           96.327456            95.227536
11    GAS           96.400596            95.123368
12    STR           96.404368            95.656232
13    ALB           96.946789            94.379895
Year: 2024, GP: 2024-2025, Mapped Index: 6
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           81.353206            87.193635
1     NOR           81.364714            87.290603
2     LEC           81.478857            87.523381
3     PIA           81.577524            87.399286
4     SAI           81.707571            87.557095
5     HAM           81.910413            87.421508
6     RUS           82.101683            87.543381
7     STR           82.616000            87.717333
8     TSU           82.953355            87.613413
9     HUL           83.073048            87.674524
10    OCO           83.373532            83.790185
11    GAS           83.467210            87.692429
12    ALO           83.877032            87.626175
13    ALB           84.493620            87.478476
Year: 2024, GP: 2024-2025, Mapped Index: 7
   Driver  LapTime_first_year  LapTime_latter_year
0     LEC          109.320740            77.397103
1     PIA          109.436091            77.403859
2     SAI          109.486688            79.593092
3     NOR          109.565429            77.356962
4     RUS          109.697364            79.837987
5     VER          109.765766            77.620705
6     HAM          109.839610            78.015769
7     TSU          112.143390            80.338053
8     ALB          112.332545            79.548842
9     GAS          112.412922            93.944143
10    ALO          113.150105            80.752833
11    STR          113.177908            80.318921
12    HUL                 NaN            80.334039
13    OCO                 NaN            79.219117
Year: 2024, GP: 2024-2025, Mapped Index: 9
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           90.473652            78.905729
1     VER           90.477304            78.755943
2     NOR           90.508464            76.325303
3     RUS           90.558275            78.752686
4     PIA           90.574899            78.782814
5     ALO           90.668812            78.909429
6     GAS           90.685319            80.009246
7     STR           90.702464            80.025377
8     OCO           90.714696            79.915377
9     HUL           90.762551            78.972171
10    TSU           91.100232            79.973101
11    SAI           91.584490            79.921362
12    ALB           91.632412            78.327826
13    LEC           95.612718            78.801857
Year: 2024, GP: 2024-2025, Mapped Index: 8
   Driver  LapTime_first_year  LapTime_latter_year
0     VER           80.306470            84.684864
1     NOR           80.340091            84.543121
2     HAM           80.576015            84.740652
3     RUS           80.644652            84.677788
4     LEC           80.650545            84.664091
5     SAI           80.776591            84.949758
6     PIA           80.817985            84.505682
7     GAS           81.246242            84.776621
8     OCO           81.395697            84.993515
9     HUL           81.430939            84.712470
10    ALO           81.688062            84.832409
11    ALB           82.436554            85.301778
12    TSU           82.525092            84.942379
Year: 2024, GP: 2024-2025, Mapped Index: 10
   Driver  LapTime_first_year  LapTime_latter_year
0     RUS           71.307014            72.715557
1     PIA           71.333859            71.862686
2     SAI           71.370859                  NaN
3     HAM           71.632958            72.238757
4     VER           71.690859                  NaN
5     NOR           71.735219            71.824186
6     HUL           72.068817            72.977000
7     GAS           72.176958            73.344174
8     LEC           72.251465            72.107329
9     OCO           72.269338            73.009841
10    STR           72.471886            73.364565
11    ALB           72.480914            80.015200
12    TSU           72.513471            73.980471
13    ALO           73.006543            72.885942
Year: 2024, GP: 2024-2025, Mapped Index: 11
   Driver  LapTime_first_year  LapTime_latter_year
0     HAM           95.135750           107.648277
1     VER           95.163923           106.586630
2     NOR           95.280885           105.549217
3     PIA           95.374769           105.341283
4     SAI           96.045712           108.568468
5     RUS           96.111424           108.341957
6     HUL           96.207327           106.569261
7     STR           96.223615           107.027543
8     ALO           96.358385           108.271000
9     ALB           96.450885           108.297745
10    TSU           96.660808           110.056761
11    LEC           97.794745           108.809574
12    OCO           99.154820           108.310809
13    GAS                 NaN           108.054234
Year: 2024, GP: 2024-2025, Mapped Index: 13
   Driver  LapTime_first_year  LapTime_latter_year
0     PIA           84.028414            81.741843
1     NOR           84.059000            81.731871
2     HAM           84.240986            83.059304
3     LEC           84.309643            82.268443
4     VER           84.333400            82.769657
5     SAI           84.358029            83.399377
6     RUS           84.633671            82.044957
7     TSU           85.132114            83.596725
8     STR           85.142357            82.705786
9     ALO           85.206414            82.575300
10    HUL           85.727145            83.369551
11    ALB           85.779101            83.468725
12    OCO           86.129246            83.572304
13    GAS           86.644091            83.588043
Year: 2024, GP: 2024-2025, Mapped Index: 12
   Driver  LapTime_first_year  LapTime_latter_year
0     RUS          109.023636           113.062415
1     HAM          109.035591           113.511659
2     PIA          109.050295           112.062537
3     LEC          109.217932           112.610439
4     VER          109.233318           112.679732
5     NOR          109.247500           112.131463
6     SAI          109.473523           114.716366
7     ALO          110.159159           114.741756
8     OCO          110.218000           114.423927
9     STR          110.455705           114.377171
10    ALB          110.470250           113.141073
11    GAS          110.486477           114.141439
12    TSU          110.767659           114.084390
13    HUL          111.042568           114.198463
Year: 2024, GP: 2024-2025, Mapped Index: 14
   Driver  LapTime_first_year  LapTime_latter_year
0     NOR           75.632208            80.757609
1     VER           75.950208            82.098889
2     LEC           75.985528            78.788808
3     PIA           76.011889            82.081236
4     SAI           76.078556            82.322569
5     RUS           76.251889            82.159764
6     HAM           76.321083            76.612636
7     GAS           76.818634            82.409417
8     ALO           76.888056            82.243861
9     HUL           76.968070            82.355194
10    STR           76.989169            82.213139
11    ALB           77.270845            82.169111
12    OCO           77.357704            82.276556
13    TSU           77.615000            82.270083
Year: 2024, GP: 2024-2025, Mapped Index: 15
   Driver  LapTime_first_year  LapTime_latter_year
0     LEC           84.542019            83.583943
1     PIA           84.592283            83.503321
2     NOR           84.658113            83.462868
3     SAI           84.836755            84.316868
4     HAM           84.972585            83.807057
5     VER           85.257717            83.100472
6     RUS           85.291358            83.720868
7     ALB           85.814774            84.054000
8     ALO           85.834377            86.729250
9     COL           86.076132            84.841788
10    OCO           86.411269            84.739615
11    GAS           86.520596            84.810808
12    HUL           86.761481                  NaN
13    STR           87.004519            84.877423
14    TSU           90.952714            84.623132
Year: 2024, GP: 2024-2025, Mapped Index: 16
   Driver  LapTime_first_year  LapTime_latter_year
0     PIA          108.493460                  NaN
1     SAI          108.607510           106.461042
2     LEC          108.677840           107.075688
3     VER          109.063102           106.058771
4     RUS          109.127900           106.456563
5     NOR          109.239420           106.974146
6     ALO          110.223980           107.996375
7     ALB          110.254460           107.852063
8     COL          110.290740           108.800915
9     HAM          110.332620           107.092625
10    BEA          110.357700           107.843500
11    HUL          110.392660           108.143396
12    GAS          110.614320           108.805660
13    OCO          110.882449           108.077833
14    STR          111.135111           108.378000
15    TSU          115.903643           106.922458
Year: 2024, GP: 2024-2025, Mapped Index: 17
   Driver  LapTime_first_year  LapTime_latter_year
0     NOR           97.622113            97.232790
1     VER           97.959935            97.222532
2     PIA           98.296677            97.266339
3     RUS           98.606629            97.134952
4     LEC           98.629048            97.876823
5     HAM           98.997081            98.429323
6     SAI           99.171129            98.903623
7     ALO           99.236787            98.436032
8     HUL           99.273951            99.531262
9     COL           99.325492            99.430443
10    TSU           99.366607            99.043213
11    OCO           99.943869            99.500000
12    STR          100.002328            99.128803
13    GAS          100.190656            99.505377
14    ALB          104.046867            99.142410
Year: 2024, GP: 2024-2025, Mapped Index: 18
   Driver  LapTime_first_year  LapTime_latter_year
0     LEC           99.808333           100.991679
1     SAI           99.997796           101.888000
2     NOR          100.158407           100.859286
3     VER          100.183926           100.717161
4     PIA          101.223745           101.247125
5     LAW          101.463074           102.024464
6     TSU          102.001340           101.658482
7     RUS          102.105691           101.314589
8     HUL          102.163255           101.739464
9     STR          102.341623           102.052482
10    COL          102.377982           102.590327
11    GAS          102.454364           102.660291
12    ALO          102.904204           101.967179
13    ALB          103.177630           102.145732
14    OCO          103.723741           102.200071
15    HAM          108.064000           101.226732
Year: 2024, GP: 2024-2025, Mapped Index: 19
   Driver  LapTime_first_year  LapTime_latter_year
0     SAI           85.292958            83.793015
1     NOR           85.359225            82.796817
2     LEC           85.777282            83.223915
3     HAM           85.923662            83.591831
4     RUS           85.976563            83.505085
5     VER           86.131803            83.234127
6     PIA           86.207437            83.389282
7     HUL           86.550286            85.005360
8     GAS           86.776957            84.609343
9     STR           86.869600            84.080129
10    COL           86.904243            84.613571
11    OCO           87.078043            83.859690
12    LAW           87.432371            96.384400
13    ALO          101.749267            84.903029
14    ALB                 NaN            84.014629
15    TSU                 NaN            83.910169
Year: 2024, GP: 2024-2025, Mapped Index: 20
An error occurred for Year: 2024, GP: 2024-2025, Mapped Index: 20. Error: The data you are trying to access has not been loaded yet. See `Session.load`
Year: 2024, GP: 2024-2025, Mapped Index: 21
An error occurred for Year: 2024, GP: 2024-2025, Mapped Index: 21. Error: The data you are trying to access has not been loaded yet. See `Session.load`
Year: 2024, GP: 2024-2025, Mapped Index: 22

100%|██████████| 5/5 [00:00<00:00,  5.83it/s]

An error occurred for Year: 2024, GP: 2024-2025, Mapped Index: 22. Error: The data you are trying to access has not been loaded yet. See `Session.load`
Year: 2024, GP: 2024-2025, Mapped Index: 23
An error occurred for Year: 2024, GP: 2024-2025, Mapped Index: 23. Error: The data you are trying to access has not been loaded yet. See `Session.load`

     Driver  LapTime_first_year  LapTime_latter_year
829     ALB          114.696227           110.470250
620     ALB          100.465088            98.511214
1282    ALB          103.177630           102.145732
493     ALB           81.016153            84.988514
317     ALB          102.143717           100.944320
...     ...                 ...                  ...
442     ZHO           72.793014            73.689143
378     ZHO           92.128581            85.764052
901     ZHO          101.666184           115.406273
641     ZHO           99.019080            98.048479
793     ZHO           98.976115           100.030700

[1301 rows x 3 columns]

### Save new dataset

In [8]:
dataset.to_csv(config.LAP_TIMES_DATASET_CSV_PATH, index=False)

### Cleaning

In [9]:
clean_dataset = dataset.dropna()
clean_dataset

     Driver  LapTime_first_year  LapTime_latter_year
829     ALB          114.696227           110.470250
620     ALB          100.465088            98.511214
1282    ALB          103.177630           102.145732
493     ALB           81.016153            84.988514
317     ALB          102.143717           100.944320
...     ...                 ...                  ...
442     ZHO           72.793014            73.689143
378     ZHO           92.128581            85.764052
901     ZHO          101.666184           115.406273
641     ZHO           99.019080            98.048479
793     ZHO           98.976115           100.030700

[1244 rows x 3 columns]

### Training

In [10]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

def data_label_split(df_windows: pd.DataFrame):
	X = df_windows.iloc[:, :-1]
	y = df_windows.iloc[:, -1]
	return X, y

def normalize_features(X: pd.DataFrame):
   scaler = StandardScaler()
   X_normalized = scaler.fit_transform(X)
   return X_normalized

In [11]:
data = clean_dataset[["LapTime_first_year", "LapTime_latter_year"]]
X, y = data_label_split(data)
X = normalize_features(X)
X.shape, y.shape

((1244, 1), (1244,))

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
X_train.shape

(995, 1)

In [13]:
params = {'colsample_bytree': 1.0, 
          'learning_rate': 0.05,
          'max_depth': 8, 
          'n_estimators': 250, 
          'subsample': 1.0}
model = xgb.XGBRegressor(**params)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=250,
             n_jobs=None, num_parallel_tree=None, ...)

In [14]:
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

MAE: 4.3374817459404404
R² Score: 0.616036903051147

In [15]:
session_last_year = sessions[2023][0]  # First session of 2023
pprint(session_last_year.laps.columns)

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [16]:
mean_lap_time_first_year = session_last_year.laps["LapTime"].dt.total_seconds().groupby(session_last_year.laps["Driver"]).mean().sort_values()
df_mean_lap_time_next_year = mean_lap_time_first_year.reset_index()
df_mean_lap_time_next_year

   Driver     LapTime
0     VER   98.890105
1     PER   99.100404
2     ALO   99.567947
3     LEC   99.644051
4     SAI   99.733123
5     HAM   99.784439
6     STR   99.846281
7     RUS   99.870333
8     BOT  100.164614
9     GAS  100.184018
10    ALB  100.465088
11    TSU  100.484316
12    SAR  100.676286
13    MAG  100.955232
14    DEV  101.058196
15    HUL  101.082982
16    ZHO  101.364018
17    NOR  102.606764
18    OCO  102.916244
19    PIA  103.275769

In [17]:
session_current_year = sessions[2024][0]  # First session of 2024

In [18]:
mean_lap_time_current_year = session_current_year.laps["LapTime"].dt.total_seconds().groupby(session_current_year.laps["Driver"]).mean().sort_values()
df_lap_time_current_year = mean_lap_time_current_year.reset_index()
df_lap_time_current_year

   Driver    LapTime
0     VER  96.574421
1     PER  96.968404
2     SAI  97.014947
3     LEC  97.270368
4     RUS  97.395263
5     NOR  97.424561
6     HAM  97.457298
7     PIA  97.558316
8     ALO  97.888228
9     STR  98.209789
10    ZHO  98.419661
11    MAG  98.447464
12    RIC  98.458929
13    TSU  98.468286
14    BOT  98.503745
15    ALB  98.511214
16    HUL  98.613821
17    OCO  98.860571
18    GAS  98.877839
19    SAR  99.327352

In [19]:
data = df_mean_lap_time_next_year.merge(df_lap_time_current_year, on="Driver", suffixes=('_2023', '_2024'))
data

   Driver  LapTime_2023  LapTime_2024
0     VER     98.890105     96.574421
1     PER     99.100404     96.968404
2     ALO     99.567947     97.888228
3     LEC     99.644051     97.270368
4     SAI     99.733123     97.014947
5     HAM     99.784439     97.457298
6     STR     99.846281     98.209789
7     RUS     99.870333     97.395263
8     BOT    100.164614     98.503745
9     GAS    100.184018     98.877839
10    ALB    100.465088     98.511214
11    TSU    100.484316     98.468286
12    SAR    100.676286     99.327352
13    MAG    100.955232     98.447464
14    HUL    101.082982     98.613821
15    ZHO    101.364018     98.419661
16    NOR    102.606764     97.424561
17    OCO    102.916244     98.860571
18    PIA    103.275769     97.558316

In [20]:
def get_laps(session: fastf1.core.Session) -> pd.DataFrame:
	"""
	Extracts lap time data for all drivers from a given session.

	Args:
		session: A fastf1 session object.

	Returns:
		A pandas DataFrame with Driver, LapNumber, and LapTime in seconds.
	"""
	if not session.laps.empty:
		laps = session.laps.copy()
		laps["LapTime"] = laps["LapTime"].dt.total_seconds()
		return laps[["Driver", "LapNumber", "LapTime"]].dropna()
	return pd.DataFrame()

def get_comparison_data(current_session: fastf1.core.Session, last_year_session: fastf1.core.Session) -> pd.DataFrame:
	"""
	Merges lap times from the same event in two consecutive years.

	Args:
		current_session: The session object for the current year.
		last_year_session: The session object for the previous year.

	Returns:
		A merged DataFrame with lap times from both years aligned by driver and lap number.
	"""
	laps_current = get_laps(current_session)
	laps_last_year = get_laps(last_year_session)

	if laps_current.empty or laps_last_year.empty:
		return pd.DataFrame()

	# Merge data on Driver and LapNumber
	merged_laps = pd.merge(
		laps_last_year, 
		laps_current, 
		on=["Driver", "LapNumber"], 
		suffixes=('_last_year', '_current_year')
	)
	return merged_laps

# --- Main processing loop ---
all_laps_data = []
# Assuming config.YEARS_TO_FETCH is sorted, start from the second year
for year in tqdm(sorted(config.YEARS_TO_FETCH)[1:-1], desc="Processing Years"):
	last_year = year - 1
	
	# Create a quick lookup map for last year's sessions by event name
	last_year_session_map = {
		s.event.EventName: s for s in sessions.get(last_year, [])
	}

	for current_session in sessions.get(year, []):
		# Find the corresponding session from the previous year
		last_year_session = last_year_session_map.get(current_session.event.EventName)
		print(f"Current Year: {year}, Event: {current_session.event.EventName}")
		if last_year_session:
			comparison_df = get_comparison_data(current_session, last_year_session)
			if not comparison_df.empty:
				all_laps_data.append(comparison_df)

# Concatenate all data into a single DataFrame
if all_laps_data:
	training_data = pd.concat(all_laps_data, ignore_index=True)
	print(f"Successfully created training data with {len(training_data)} samples.")
	print(training_data.head())
else:
	print("No matching sessions found to create training data.")
	training_data = pd.DataFrame()

Processing Years:   0%|          | 0/3 [00:00<?, ?it/s]

Current Year: 2022, Event: Bahrain Grand Prix
Current Year: 2022, Event: Saudi Arabian Grand Prix
Current Year: 2022, Event: Australian Grand Prix
Current Year: 2022, Event: Emilia Romagna Grand Prix
Current Year: 2022, Event: Miami Grand Prix
Current Year: 2022, Event: Spanish Grand Prix
Current Year: 2022, Event: Monaco Grand Prix
Current Year: 2022, Event: Azerbaijan Grand Prix
Current Year: 2022, Event: Canadian Grand Prix
Current Year: 2022, Event: British Grand Prix
Current Year: 2022, Event: Austrian Grand Prix
Current Year: 2022, Event: French Grand Prix
Current Year: 2022, Event: Hungarian Grand Prix
Current Year: 2022, Event: Belgian Grand Prix
Current Year: 2022, Event: Dutch Grand Prix
Current Year: 2022, Event: Italian Grand Prix
Current Year: 2022, Event: Singapore Grand Prix
Current Year: 2022, Event: Japanese Grand Prix
Current Year: 2022, Event: United States Grand Prix
Current Year: 2022, Event: Mexico City Grand Prix
Current Year: 2022, Event: São Paulo Grand Prix

Processing Years:  33%|███▎      | 1/3 [00:00<00:00,  4.37it/s]

Current Year: 2022, Event: Abu Dhabi Grand Prix
Current Year: 2023, Event: Bahrain Grand Prix
Current Year: 2023, Event: Saudi Arabian Grand Prix
Current Year: 2023, Event: Australian Grand Prix
Current Year: 2023, Event: Azerbaijan Grand Prix
Current Year: 2023, Event: Miami Grand Prix
Current Year: 2023, Event: Monaco Grand Prix
Current Year: 2023, Event: Spanish Grand Prix
Current Year: 2023, Event: Canadian Grand Prix
Current Year: 2023, Event: Austrian Grand Prix
Current Year: 2023, Event: British Grand Prix
Current Year: 2023, Event: Hungarian Grand Prix
Current Year: 2023, Event: Belgian Grand Prix
Current Year: 2023, Event: Dutch Grand Prix
Current Year: 2023, Event: Italian Grand Prix
Current Year: 2023, Event: Singapore Grand Prix
Current Year: 2023, Event: Japanese Grand Prix
Current Year: 2023, Event: Qatar Grand Prix
Current Year: 2023, Event: United States Grand Prix
Current Year: 2023, Event: Mexico City Grand Prix
Current Year: 2023, Event: São Paulo Grand Prix
Current Year: 2023, Event: Las Vegas Grand Prix
Current Year: 2023, Event: Abu Dhabi Grand Prix

Processing Years:  67%|██████▋   | 2/3 [00:00<00:00,  3.66it/s]

Current Year: 2024, Event: Bahrain Grand Prix
Current Year: 2024, Event: Saudi Arabian Grand Prix
Current Year: 2024, Event: Australian Grand Prix
Current Year: 2024, Event: Japanese Grand Prix
Current Year: 2024, Event: Chinese Grand Prix
Current Year: 2024, Event: Miami Grand Prix
Current Year: 2024, Event: Emilia Romagna Grand Prix
Current Year: 2024, Event: Monaco Grand Prix
Current Year: 2024, Event: Canadian Grand Prix
Current Year: 2024, Event: Spanish Grand Prix
Current Year: 2024, Event: Austrian Grand Prix
Current Year: 2024, Event: British Grand Prix
Current Year: 2024, Event: Hungarian Grand Prix
Current Year: 2024, Event: Belgian Grand Prix
Current Year: 2024, Event: Dutch Grand Prix
Current Year: 2024, Event: Italian Grand Prix
Current Year: 2024, Event: Azerbaijan Grand Prix
Current Year: 2024, Event: Singapore Grand Prix

Processing Years: 100%|██████████| 3/3 [00:00<00:00,  3.66it/s]

Current Year: 2024, Event: United States Grand Prix
Current Year: 2024, Event: Mexico City Grand Prix
Current Year: 2024, Event: São Paulo Grand Prix
Current Year: 2024, Event: Las Vegas Grand Prix
Current Year: 2024, Event: Qatar Grand Prix
Current Year: 2024, Event: Abu Dhabi Grand Prix
Successfully created training data with 49750 samples.
  Driver  LapNumber  LapTime_last_year  LapTime_current_year
0    HAM        1.0            119.538               101.555
1    HAM        2.0            142.712                99.002
2    HAM        4.0            104.932                98.892
3    HAM        5.0            105.139                98.923
4    HAM        6.0             96.169                99.707

In [21]:
training_data

      Driver  LapNumber  LapTime_last_year  LapTime_current_year
0        HAM        1.0            119.538               101.555
1        HAM        2.0            142.712                99.002
2        HAM        4.0            104.932                98.892
3        HAM        5.0            105.139                98.923
4        HAM        6.0             96.169                99.707
...      ...        ...                ...                   ...
49745    MAG       53.0             90.445                90.215
49746    MAG       54.0             90.207                91.204
49747    MAG       55.0             90.252                91.958
49748    MAG       56.0             90.429               112.994
49749    MAG       57.0             91.256                85.637

[49750 rows x 4 columns]

In [22]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

def data_label_split(df_windows: pd.DataFrame):
	X = df_windows.iloc[:, :-1]
	y = df_windows.iloc[:, -1]
	return X, y

def normalize_features(X: pd.DataFrame):
   scaler = StandardScaler()
   X_normalized = scaler.fit_transform(X)
   return X_normalized

In [32]:
data = training_data[["LapTime_last_year", "LapTime_current_year"]]
X, y = data_label_split(data)
X = normalize_features(X)
X.shape, y.shape

((49750, 1), (49750,))

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
X_train.shape

(39800, 1)

In [54]:
params = {'colsample_bytree': 1.0, 
          'learning_rate': 0.05,
          'max_depth': 8, 
          'n_estimators': 250, 
          'subsample': 1.0}
model = xgb.XGBRegressor(**params)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=250,
             n_jobs=None, num_parallel_tree=None, ...)

In [55]:
X_test.mean()

np.float64(-0.011291671494322263)

In [56]:
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

MAE: 6.9778566216458255
R² Score: 0.04583937880311373

In [57]:
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

MAE: 6.9778566216458255
R² Score: 0.04583937880311373

In [58]:
pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

        Actual   Predicted
27771   75.390   83.590958
15528   82.720   97.514534
3578   108.949   83.694176
33501   76.561   99.293877
36141   81.139   82.857925
...        ...         ...
36416   78.385   85.787079
12111   78.000   83.618111
31508   83.070  100.138412
43873  108.467  105.612625
15552   80.816   83.438393

[9950 rows x 2 columns]